//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.01 at 06:02:48 PM IST 
//


package org.mismo.residential._2009.schemas;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ABOUT_VERSION complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ABOUT_VERSION">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AboutVersionIdentifier" type="{http://www.mismo.org/residential/2009/schemas}MISMOIdentifier" minOccurs="0"/>
 *         &lt;element name="CreatedDatetime" type="{http://www.mismo.org/residential/2009/schemas}MISMODatetime" minOccurs="0"/>
 *         &lt;element name="DataVersionIdentifier" type="{http://www.mismo.org/residential/2009/schemas}MISMOIdentifier" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ABOUT_VERSION", propOrder = {
    "aboutVersionIdentifier",
    "createdDatetime",
    "dataVersionIdentifier"
})
public class ABOUTVERSION {

    @XmlElement(name = "AboutVersionIdentifier")
    protected MISMOIdentifier aboutVersionIdentifier;
    @XmlElement(name = "CreatedDatetime")
    protected MISMODatetime createdDatetime;
    @XmlElement(name = "DataVersionIdentifier")
    protected MISMOIdentifier dataVersionIdentifier;

    /**
     * Gets the value of the aboutVersionIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link MISMOIdentifier }
     *     
     */
    public MISMOIdentifier getAboutVersionIdentifier() {
        return aboutVersionIdentifier;
    }

    /**
     * Sets the value of the aboutVersionIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link MISMOIdentifier }
     *     
     */
    public void setAboutVersionIdentifier(MISMOIdentifier value) {
        this.aboutVersionIdentifier = value;
    }

    /**
     * Gets the value of the createdDatetime property.
     * 
     * @return
     *     possible object is
     *     {@link MISMODatetime }
     *     
     */
    public MISMODatetime getCreatedDatetime() {
        return createdDatetime;
    }

    /**
     * Sets the value of the createdDatetime property.
     * 
     * @param value
     *     allowed object is
     *     {@link MISMODatetime }
     *     
     */
    public void setCreatedDatetime(MISMODatetime value) {
        this.createdDatetime = value;
    }

    /**
     * Gets the value of the dataVersionIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link MISMOIdentifier }
     *     
     */
    public MISMOIdentifier getDataVersionIdentifier() {
        return dataVersionIdentifier;
    }

    /**
     * Sets the value of the dataVersionIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link MISMOIdentifier }
     *     
     */
    public void setDataVersionIdentifier(MISMOIdentifier value) {
        this.dataVersionIdentifier = value;
    }

}
