//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.01 at 06:02:48 PM IST 
//


package org.mismo.residential._2009.schemas;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ABOUT_VERSIONS complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ABOUT_VERSIONS">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ABOUT_VERSION" type="{http://www.mismo.org/residential/2009/schemas}ABOUT_VERSION"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ABOUT_VERSIONS", propOrder = {
    "aboutversion"
})
public class ABOUTVERSIONS {

    @XmlElement(name = "ABOUT_VERSION", required = true)
    protected ABOUTVERSION aboutversion;

    /**
     * Gets the value of the aboutversion property.
     * 
     * @return
     *     possible object is
     *     {@link ABOUTVERSION }
     *     
     */
    public ABOUTVERSION getABOUTVERSION() {
        return aboutversion;
    }

    /**
     * Sets the value of the aboutversion property.
     * 
     * @param value
     *     allowed object is
     *     {@link ABOUTVERSION }
     *     
     */
    public void setABOUTVERSION(ABOUTVERSION value) {
        this.aboutversion = value;
    }

}
