//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.01 at 06:02:48 PM IST 
//


package org.mismo.residential._2009.schemas;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AutomatedUnderwritingSystemBase.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="AutomatedUnderwritingSystemBase">
 *   &lt;restriction base="{http://www.mismo.org/residential/2009/schemas}MISMOEnum_Base">
 *     &lt;enumeration value="Assetwise"/>
 *     &lt;enumeration value="Capstone"/>
 *     &lt;enumeration value="Clues"/>
 *     &lt;enumeration value="DesktopUnderwriter"/>
 *     &lt;enumeration value="ECS"/>
 *     &lt;enumeration value="FHAScorecard"/>
 *     &lt;enumeration value="LoanProspector"/>
 *     &lt;enumeration value="Other"/>
 *     &lt;enumeration value="Strategyware"/>
 *     &lt;enumeration value="Zippy"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "AutomatedUnderwritingSystemBase")
@XmlEnum
public enum AutomatedUnderwritingSystemBase {


    /**
     * GMAC / RFC
     * 
     */
    @XmlEnumValue("Assetwise")
    ASSETWISE("Assetwise"),
    @XmlEnumValue("Capstone")
    CAPSTONE("Capstone"),

    /**
     * Bank of America
     * 
     */
    @XmlEnumValue("Clues")
    CLUES("Clues"),

    /**
     * Fannie Mae
     * 
     */
    @XmlEnumValue("DesktopUnderwriter")
    DESKTOP_UNDERWRITER("DesktopUnderwriter"),

    /**
     * Wells Fargo
     * 
     */
    ECS("ECS"),

    /**
     * The loan scoring tool used by lenders to manage workflow and expedite the endorsement process for FHA loans. The FHA TOTAL Scorecard evaluates the overall creditworthiness of the applicants and determines an associated risk level of a loan's eligibility for insurance by FHA. 
     * 
     */
    @XmlEnumValue("FHAScorecard")
    FHA_SCORECARD("FHAScorecard"),

    /**
     *  Freddie Mac
     * 
     */
    @XmlEnumValue("LoanProspector")
    LOAN_PROSPECTOR("LoanProspector"),
    @XmlEnumValue("Other")
    OTHER("Other"),
    @XmlEnumValue("Strategyware")
    STRATEGYWARE("Strategyware"),

    /**
     * Chase
     * 
     */
    @XmlEnumValue("Zippy")
    ZIPPY("Zippy");
    private final String value;

    AutomatedUnderwritingSystemBase(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static AutomatedUnderwritingSystemBase fromValue(String v) {
        for (AutomatedUnderwritingSystemBase c: AutomatedUnderwritingSystemBase.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
