//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.01 at 06:02:48 PM IST 
//


package org.mismo.residential._2009.schemas;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AutomatedUnderwritingSystemTypeOtherDescriptionBase.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="AutomatedUnderwritingSystemTypeOtherDescriptionBase">
 *   &lt;restriction base="{http://www.mismo.org/residential/2009/schemas}MISMOEnum_Base">
 *     &lt;enumeration value="DecisionEngine"/>
 *     &lt;enumeration value="FirstMortgageCreditScore"/>
 *     &lt;enumeration value="GuaranteedUnderwritingSystem"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "AutomatedUnderwritingSystemTypeOtherDescriptionBase")
@XmlEnum
public enum AutomatedUnderwritingSystemTypeOtherDescriptionBase {


    /**
     * Citibank
     * 
     */
    @XmlEnumValue("DecisionEngine")
    DECISION_ENGINE("DecisionEngine"),

    /**
     * Citibank
     * 
     */
    @XmlEnumValue("FirstMortgageCreditScore")
    FIRST_MORTGAGE_CREDIT_SCORE("FirstMortgageCreditScore"),

    /**
     * USDA Rural Development
     * 
     */
    @XmlEnumValue("GuaranteedUnderwritingSystem")
    GUARANTEED_UNDERWRITING_SYSTEM("GuaranteedUnderwritingSystem");
    private final String value;

    AutomatedUnderwritingSystemTypeOtherDescriptionBase(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static AutomatedUnderwritingSystemTypeOtherDescriptionBase fromValue(String v) {
        for (AutomatedUnderwritingSystemTypeOtherDescriptionBase c: AutomatedUnderwritingSystemTypeOtherDescriptionBase.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
