//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.01 at 06:02:48 PM IST 
//


package org.mismo.residential._2009.schemas;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AUTOMATED_UNDERWRITING complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AUTOMATED_UNDERWRITING">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AutomatedUnderwritingCaseIdentifier" type="{http://www.mismo.org/residential/2009/schemas}MISMOIdentifier" minOccurs="0"/>
 *         &lt;element name="AutomatedUnderwritingSystemType" type="{http://www.mismo.org/residential/2009/schemas}AutomatedUnderwritingSystemEnum" minOccurs="0"/>
 *         &lt;element name="AutomatedUnderwritingSystemTypeOtherDescription" type="{http://www.mismo.org/residential/2009/schemas}AutomatedUnderwritingSystemTypeOtherDescriptionEnum" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AUTOMATED_UNDERWRITING", propOrder = {
    "automatedUnderwritingCaseIdentifier",
    "automatedUnderwritingSystemType",
    "automatedUnderwritingSystemTypeOtherDescription"
})
public class AUTOMATEDUNDERWRITING {

    @XmlElement(name = "AutomatedUnderwritingCaseIdentifier")
    protected MISMOIdentifier automatedUnderwritingCaseIdentifier;
    @XmlElement(name = "AutomatedUnderwritingSystemType")
    protected AutomatedUnderwritingSystemEnum automatedUnderwritingSystemType;
    @XmlElement(name = "AutomatedUnderwritingSystemTypeOtherDescription")
    protected AutomatedUnderwritingSystemTypeOtherDescriptionEnum automatedUnderwritingSystemTypeOtherDescription;

    /**
     * Gets the value of the automatedUnderwritingCaseIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link MISMOIdentifier }
     *     
     */
    public MISMOIdentifier getAutomatedUnderwritingCaseIdentifier() {
        return automatedUnderwritingCaseIdentifier;
    }

    /**
     * Sets the value of the automatedUnderwritingCaseIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link MISMOIdentifier }
     *     
     */
    public void setAutomatedUnderwritingCaseIdentifier(MISMOIdentifier value) {
        this.automatedUnderwritingCaseIdentifier = value;
    }

    /**
     * Gets the value of the automatedUnderwritingSystemType property.
     * 
     * @return
     *     possible object is
     *     {@link AutomatedUnderwritingSystemEnum }
     *     
     */
    public AutomatedUnderwritingSystemEnum getAutomatedUnderwritingSystemType() {
        return automatedUnderwritingSystemType;
    }

    /**
     * Sets the value of the automatedUnderwritingSystemType property.
     * 
     * @param value
     *     allowed object is
     *     {@link AutomatedUnderwritingSystemEnum }
     *     
     */
    public void setAutomatedUnderwritingSystemType(AutomatedUnderwritingSystemEnum value) {
        this.automatedUnderwritingSystemType = value;
    }

    /**
     * Gets the value of the automatedUnderwritingSystemTypeOtherDescription property.
     * 
     * @return
     *     possible object is
     *     {@link AutomatedUnderwritingSystemTypeOtherDescriptionEnum }
     *     
     */
    public AutomatedUnderwritingSystemTypeOtherDescriptionEnum getAutomatedUnderwritingSystemTypeOtherDescription() {
        return automatedUnderwritingSystemTypeOtherDescription;
    }

    /**
     * Sets the value of the automatedUnderwritingSystemTypeOtherDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link AutomatedUnderwritingSystemTypeOtherDescriptionEnum }
     *     
     */
    public void setAutomatedUnderwritingSystemTypeOtherDescription(AutomatedUnderwritingSystemTypeOtherDescriptionEnum value) {
        this.automatedUnderwritingSystemTypeOtherDescription = value;
    }

}
