//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.01 at 06:02:48 PM IST 
//


package org.mismo.residential._2009.schemas;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BUYDOWN_OCCURRENCE complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BUYDOWN_OCCURRENCE">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="BuydownInitialEffectiveInterestRatePercent" type="{http://www.mismo.org/residential/2009/schemas}MISMOPercent" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BUYDOWN_OCCURRENCE", propOrder = {
    "buydownInitialEffectiveInterestRatePercent"
})
public class BUYDOWNOCCURRENCE {

    @XmlElement(name = "BuydownInitialEffectiveInterestRatePercent")
    protected MISMOPercent buydownInitialEffectiveInterestRatePercent;

    /**
     * Gets the value of the buydownInitialEffectiveInterestRatePercent property.
     * 
     * @return
     *     possible object is
     *     {@link MISMOPercent }
     *     
     */
    public MISMOPercent getBuydownInitialEffectiveInterestRatePercent() {
        return buydownInitialEffectiveInterestRatePercent;
    }

    /**
     * Sets the value of the buydownInitialEffectiveInterestRatePercent property.
     * 
     * @param value
     *     allowed object is
     *     {@link MISMOPercent }
     *     
     */
    public void setBuydownInitialEffectiveInterestRatePercent(MISMOPercent value) {
        this.buydownInitialEffectiveInterestRatePercent = value;
    }

}
