//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.01 at 06:02:48 PM IST 
//


package org.mismo.residential._2009.schemas;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Describes the provision, schedule, and structure of funds used to reduce the interest rate and/or payment on a mortgage note a temporary basis. A permanent buydown is covered by points paid at origiation, see Borrower Paid Discount Points Total Amount.
 * 
 * <p>Java class for BUYDOWN complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BUYDOWN">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="BUYDOWN_OCCURRENCES" type="{http://www.mismo.org/residential/2009/schemas}BUYDOWN_OCCURRENCES" minOccurs="0"/>
 *         &lt;element name="BUYDOWN_RULE" type="{http://www.mismo.org/residential/2009/schemas}BUYDOWN_RULE" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BUYDOWN", propOrder = {
    "buydownoccurrences",
    "buydownrule"
})
public class BUYDOWN {

    @XmlElement(name = "BUYDOWN_OCCURRENCES")
    protected BUYDOWNOCCURRENCES buydownoccurrences;
    @XmlElement(name = "BUYDOWN_RULE")
    protected BUYDOWNRULE buydownrule;

    /**
     * Gets the value of the buydownoccurrences property.
     * 
     * @return
     *     possible object is
     *     {@link BUYDOWNOCCURRENCES }
     *     
     */
    public BUYDOWNOCCURRENCES getBUYDOWNOCCURRENCES() {
        return buydownoccurrences;
    }

    /**
     * Sets the value of the buydownoccurrences property.
     * 
     * @param value
     *     allowed object is
     *     {@link BUYDOWNOCCURRENCES }
     *     
     */
    public void setBUYDOWNOCCURRENCES(BUYDOWNOCCURRENCES value) {
        this.buydownoccurrences = value;
    }

    /**
     * Gets the value of the buydownrule property.
     * 
     * @return
     *     possible object is
     *     {@link BUYDOWNRULE }
     *     
     */
    public BUYDOWNRULE getBUYDOWNRULE() {
        return buydownrule;
    }

    /**
     * Sets the value of the buydownrule property.
     * 
     * @param value
     *     allowed object is
     *     {@link BUYDOWNRULE }
     *     
     */
    public void setBUYDOWNRULE(BUYDOWNRULE value) {
        this.buydownrule = value;
    }

}
