//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.01 at 06:02:48 PM IST 
//


package org.mismo.residential._2009.schemas;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Information on the amount, type and source of funds needed to close the real estate transaction. 
 * 
 * <p>Java class for CLOSING_COST_FUND complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CLOSING_COST_FUND">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ClosingCostFundAmount" type="{http://www.mismo.org/residential/2009/schemas}MISMOAmount" minOccurs="0"/>
 *         &lt;element name="FundsType" type="{http://www.mismo.org/residential/2009/schemas}FundsEnum" minOccurs="0"/>
 *         &lt;element name="IntegratedDisclosureSectionType" type="{http://www.mismo.org/residential/2009/schemas}IntegratedDisclosureSectionEnum" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CLOSING_COST_FUND", propOrder = {
    "closingCostFundAmount",
    "fundsType",
    "integratedDisclosureSectionType"
})
public class CLOSINGCOSTFUND {

    @XmlElement(name = "ClosingCostFundAmount")
    protected MISMOAmount closingCostFundAmount;
    @XmlElement(name = "FundsType")
    protected FundsEnum fundsType;
    @XmlElement(name = "IntegratedDisclosureSectionType")
    protected IntegratedDisclosureSectionEnum integratedDisclosureSectionType;

    /**
     * Gets the value of the closingCostFundAmount property.
     * 
     * @return
     *     possible object is
     *     {@link MISMOAmount }
     *     
     */
    public MISMOAmount getClosingCostFundAmount() {
        return closingCostFundAmount;
    }

    /**
     * Sets the value of the closingCostFundAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link MISMOAmount }
     *     
     */
    public void setClosingCostFundAmount(MISMOAmount value) {
        this.closingCostFundAmount = value;
    }

    /**
     * Gets the value of the fundsType property.
     * 
     * @return
     *     possible object is
     *     {@link FundsEnum }
     *     
     */
    public FundsEnum getFundsType() {
        return fundsType;
    }

    /**
     * Sets the value of the fundsType property.
     * 
     * @param value
     *     allowed object is
     *     {@link FundsEnum }
     *     
     */
    public void setFundsType(FundsEnum value) {
        this.fundsType = value;
    }

    /**
     * Gets the value of the integratedDisclosureSectionType property.
     * 
     * @return
     *     possible object is
     *     {@link IntegratedDisclosureSectionEnum }
     *     
     */
    public IntegratedDisclosureSectionEnum getIntegratedDisclosureSectionType() {
        return integratedDisclosureSectionType;
    }

    /**
     * Sets the value of the integratedDisclosureSectionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link IntegratedDisclosureSectionEnum }
     *     
     */
    public void setIntegratedDisclosureSectionType(IntegratedDisclosureSectionEnum value) {
        this.integratedDisclosureSectionType = value;
    }

}
