//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.01 at 06:02:48 PM IST 
//


package org.mismo.residential._2009.schemas;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * The root element for all use cases where a collection of Loans need to ne delivered.
 * 
 * <p>Java class for DEALS complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DEALS">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DEAL" type="{http://www.mismo.org/residential/2009/schemas}DEAL"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DEALS", propOrder = {
    "deal"
})
public class DEALS {

    @XmlElement(name = "DEAL", required = true)
    protected DEAL deal;

    /**
     * Gets the value of the deal property.
     * 
     * @return
     *     possible object is
     *     {@link DEAL }
     *     
     */
    public DEAL getDEAL() {
        return deal;
    }

    /**
     * Sets the value of the deal property.
     * 
     * @param value
     *     allowed object is
     *     {@link DEAL }
     *     
     */
    public void setDEAL(DEAL value) {
        this.deal = value;
    }

}
