//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.01 at 06:02:48 PM IST 
//


package org.mismo.residential._2009.schemas;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Contains doucment type information.
 * 
 * <p>Java class for DOCUMENT_CLASS complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DOCUMENT_CLASS">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DocumentType" type="{http://www.mismo.org/residential/2009/schemas}DocumentEnum"/>
 *         &lt;element name="DocumentTypeOtherDescription" type="{http://www.mismo.org/residential/2009/schemas}DocumentTypeOtherDescriptionEnum"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DOCUMENT_CLASS", propOrder = {
    "documentType",
    "documentTypeOtherDescription"
})
public class DOCUMENTCLASS {

    @XmlElement(name = "DocumentType", required = true)
    protected DocumentEnum documentType;
    @XmlElement(name = "DocumentTypeOtherDescription", required = true)
    protected DocumentTypeOtherDescriptionEnum documentTypeOtherDescription;

    /**
     * Gets the value of the documentType property.
     * 
     * @return
     *     possible object is
     *     {@link DocumentEnum }
     *     
     */
    public DocumentEnum getDocumentType() {
        return documentType;
    }

    /**
     * Sets the value of the documentType property.
     * 
     * @param value
     *     allowed object is
     *     {@link DocumentEnum }
     *     
     */
    public void setDocumentType(DocumentEnum value) {
        this.documentType = value;
    }

    /**
     * Gets the value of the documentTypeOtherDescription property.
     * 
     * @return
     *     possible object is
     *     {@link DocumentTypeOtherDescriptionEnum }
     *     
     */
    public DocumentTypeOtherDescriptionEnum getDocumentTypeOtherDescription() {
        return documentTypeOtherDescription;
    }

    /**
     * Sets the value of the documentTypeOtherDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link DocumentTypeOtherDescriptionEnum }
     *     
     */
    public void setDocumentTypeOtherDescription(DocumentTypeOtherDescriptionEnum value) {
        this.documentTypeOtherDescription = value;
    }

}
