//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.01 at 06:02:48 PM IST 
//


package org.mismo.residential._2009.schemas;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Contains information about a specific instance of a document that describes its use (as opposed to its contents).
 * 
 * <p>Java class for DOCUMENT_CLASSIFICATION complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DOCUMENT_CLASSIFICATION">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DOCUMENT_CLASSES" type="{http://www.mismo.org/residential/2009/schemas}DOCUMENT_CLASSES"/>
 *         &lt;element name="DOCUMENT_CLASSIFICATION_DETAIL" type="{http://www.mismo.org/residential/2009/schemas}DOCUMENT_CLASSIFICATION_DETAIL"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DOCUMENT_CLASSIFICATION", propOrder = {
    "documentclasses",
    "documentclassificationdetail"
})
public class DOCUMENTCLASSIFICATION {

    @XmlElement(name = "DOCUMENT_CLASSES", required = true)
    protected DOCUMENTCLASSES documentclasses;
    @XmlElement(name = "DOCUMENT_CLASSIFICATION_DETAIL", required = true)
    protected DOCUMENTCLASSIFICATIONDETAIL documentclassificationdetail;

    /**
     * Gets the value of the documentclasses property.
     * 
     * @return
     *     possible object is
     *     {@link DOCUMENTCLASSES }
     *     
     */
    public DOCUMENTCLASSES getDOCUMENTCLASSES() {
        return documentclasses;
    }

    /**
     * Sets the value of the documentclasses property.
     * 
     * @param value
     *     allowed object is
     *     {@link DOCUMENTCLASSES }
     *     
     */
    public void setDOCUMENTCLASSES(DOCUMENTCLASSES value) {
        this.documentclasses = value;
    }

    /**
     * Gets the value of the documentclassificationdetail property.
     * 
     * @return
     *     possible object is
     *     {@link DOCUMENTCLASSIFICATIONDETAIL }
     *     
     */
    public DOCUMENTCLASSIFICATIONDETAIL getDOCUMENTCLASSIFICATIONDETAIL() {
        return documentclassificationdetail;
    }

    /**
     * Sets the value of the documentclassificationdetail property.
     * 
     * @param value
     *     allowed object is
     *     {@link DOCUMENTCLASSIFICATIONDETAIL }
     *     
     */
    public void setDOCUMENTCLASSIFICATIONDETAIL(DOCUMENTCLASSIFICATIONDETAIL value) {
        this.documentclassificationdetail = value;
    }

}
