//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.01 at 06:02:48 PM IST 
//


package org.mismo.residential._2009.schemas;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * A DOCUMENT element contains or refers to an electronic record that reports one or more aspects of a business transaction.    A DOCUMENT element has types, purposes, and uses which are described in the DOCUMENT_CLASSIFICATION element. A DOCUMENT element contains one or more VIEW elements which allow rendering for human consumption, for example on a computer display or printed on paper.  A DOCUMENT element may contain a DEAL_SETS element with data related to the DOCUMENT.  A DOCUMENT element may also contain a MAP element that relates data in the DOCUMENT to populated fields in one or more VIEW elements. A DOCUMENT may contain SIGNATORY elements used to represent the legally binding signatures of the parties named in the electronic record. A DOCUMENT also supports SYSTEM_SIGNATURE elements to create digital tamper-evident seals over portions or all of the DOCUMENT. Finally, a DOCUMENT may contain one or more AUDIT_TRAIL_ENTRY elements that list events which occurred to the DOCUMENT. A DOCUMENT is also known as a MISMO V3 SMART Doc® electronic document. A DOCUMENT may be delivered within a MISMO V3 MESSAGE, or a DOCUMENT element may be the root element of a standalone resource that may be validated with the model schema.
 * 
 * <p>Java class for DOCUMENT complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DOCUMENT">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AUDIT_TRAIL" type="{http://www.mismo.org/residential/2009/schemas}AUDIT_TRAIL" minOccurs="0"/>
 *         &lt;element name="DEAL_SETS" type="{http://www.mismo.org/residential/2009/schemas}DEAL_SETS"/>
 *         &lt;element name="RELATIONSHIPS" type="{http://www.mismo.org/residential/2009/schemas}RELATIONSHIPS"/>
 *         &lt;element name="SIGNATORIES" type="{http://www.mismo.org/residential/2009/schemas}SIGNATORIES" minOccurs="0"/>
 *         &lt;element name="SYSTEM_SIGNATURES" type="{http://www.mismo.org/residential/2009/schemas}SYSTEM_SIGNATURES" minOccurs="0"/>
 *         &lt;element name="VIEWS" type="{http://www.mismo.org/residential/2009/schemas}VIEWS"/>
 *         &lt;element name="ABOUT_VERSIONS" type="{http://www.mismo.org/residential/2009/schemas}ABOUT_VERSIONS"/>
 *         &lt;element name="DOCUMENT_CLASSIFICATION" type="{http://www.mismo.org/residential/2009/schemas}DOCUMENT_CLASSIFICATION"/>
 *       &lt;/sequence>
 *       &lt;attribute name="MISMOReferenceModelIdentifier" type="{http://www.mismo.org/residential/2009/schemas}MISMOReferenceModelIdentifier" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DOCUMENT", propOrder = {
    "audittrail",
    "dealsets",
    "relationships",
    "signatories",
    "systemsignatures",
    "views",
    "aboutversions",
    "documentclassification"
})
public class DOCUMENT {

    @XmlElement(name = "AUDIT_TRAIL")
    protected AUDITTRAIL audittrail;
    @XmlElement(name = "DEAL_SETS", required = true)
    protected DEALSETS dealsets;
    @XmlElement(name = "RELATIONSHIPS", required = true)
    protected RELATIONSHIPS relationships;
    @XmlElement(name = "SIGNATORIES")
    protected SIGNATORIES signatories;
    @XmlElement(name = "SYSTEM_SIGNATURES")
    protected SYSTEMSIGNATURES systemsignatures;
    @XmlElement(name = "VIEWS", required = true)
    protected VIEWS views;
    @XmlElement(name = "ABOUT_VERSIONS", required = true)
    protected ABOUTVERSIONS aboutversions;
    @XmlElement(name = "DOCUMENT_CLASSIFICATION", required = true)
    protected DOCUMENTCLASSIFICATION documentclassification;
    @XmlAttribute(name = "MISMOReferenceModelIdentifier")
    protected String mismoReferenceModelIdentifier;

    /**
     * Gets the value of the audittrail property.
     * 
     * @return
     *     possible object is
     *     {@link AUDITTRAIL }
     *     
     */
    public AUDITTRAIL getAUDITTRAIL() {
        return audittrail;
    }

    /**
     * Sets the value of the audittrail property.
     * 
     * @param value
     *     allowed object is
     *     {@link AUDITTRAIL }
     *     
     */
    public void setAUDITTRAIL(AUDITTRAIL value) {
        this.audittrail = value;
    }

    /**
     * Gets the value of the dealsets property.
     * 
     * @return
     *     possible object is
     *     {@link DEALSETS }
     *     
     */
    public DEALSETS getDEALSETS() {
        return dealsets;
    }

    /**
     * Sets the value of the dealsets property.
     * 
     * @param value
     *     allowed object is
     *     {@link DEALSETS }
     *     
     */
    public void setDEALSETS(DEALSETS value) {
        this.dealsets = value;
    }

    /**
     * Gets the value of the relationships property.
     * 
     * @return
     *     possible object is
     *     {@link RELATIONSHIPS }
     *     
     */
    public RELATIONSHIPS getRELATIONSHIPS() {
        return relationships;
    }

    /**
     * Sets the value of the relationships property.
     * 
     * @param value
     *     allowed object is
     *     {@link RELATIONSHIPS }
     *     
     */
    public void setRELATIONSHIPS(RELATIONSHIPS value) {
        this.relationships = value;
    }

    /**
     * Gets the value of the signatories property.
     * 
     * @return
     *     possible object is
     *     {@link SIGNATORIES }
     *     
     */
    public SIGNATORIES getSIGNATORIES() {
        return signatories;
    }

    /**
     * Sets the value of the signatories property.
     * 
     * @param value
     *     allowed object is
     *     {@link SIGNATORIES }
     *     
     */
    public void setSIGNATORIES(SIGNATORIES value) {
        this.signatories = value;
    }

    /**
     * Gets the value of the systemsignatures property.
     * 
     * @return
     *     possible object is
     *     {@link SYSTEMSIGNATURES }
     *     
     */
    public SYSTEMSIGNATURES getSYSTEMSIGNATURES() {
        return systemsignatures;
    }

    /**
     * Sets the value of the systemsignatures property.
     * 
     * @param value
     *     allowed object is
     *     {@link SYSTEMSIGNATURES }
     *     
     */
    public void setSYSTEMSIGNATURES(SYSTEMSIGNATURES value) {
        this.systemsignatures = value;
    }

    /**
     * Gets the value of the views property.
     * 
     * @return
     *     possible object is
     *     {@link VIEWS }
     *     
     */
    public VIEWS getVIEWS() {
        return views;
    }

    /**
     * Sets the value of the views property.
     * 
     * @param value
     *     allowed object is
     *     {@link VIEWS }
     *     
     */
    public void setVIEWS(VIEWS value) {
        this.views = value;
    }

    /**
     * Gets the value of the aboutversions property.
     * 
     * @return
     *     possible object is
     *     {@link ABOUTVERSIONS }
     *     
     */
    public ABOUTVERSIONS getABOUTVERSIONS() {
        return aboutversions;
    }

    /**
     * Sets the value of the aboutversions property.
     * 
     * @param value
     *     allowed object is
     *     {@link ABOUTVERSIONS }
     *     
     */
    public void setABOUTVERSIONS(ABOUTVERSIONS value) {
        this.aboutversions = value;
    }

    /**
     * Gets the value of the documentclassification property.
     * 
     * @return
     *     possible object is
     *     {@link DOCUMENTCLASSIFICATION }
     *     
     */
    public DOCUMENTCLASSIFICATION getDOCUMENTCLASSIFICATION() {
        return documentclassification;
    }

    /**
     * Sets the value of the documentclassification property.
     * 
     * @param value
     *     allowed object is
     *     {@link DOCUMENTCLASSIFICATION }
     *     
     */
    public void setDOCUMENTCLASSIFICATION(DOCUMENTCLASSIFICATION value) {
        this.documentclassification = value;
    }

    /**
     * Gets the value of the mismoReferenceModelIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMISMOReferenceModelIdentifier() {
        return mismoReferenceModelIdentifier;
    }

    /**
     * Sets the value of the mismoReferenceModelIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMISMOReferenceModelIdentifier(String value) {
        this.mismoReferenceModelIdentifier = value;
    }

}
