//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.01 at 06:02:48 PM IST 
//


package org.mismo.residential._2009.schemas;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * General information about a particular escrow type, when it was last disbursed, the amount collected each month towards that escrow type, how often payments are disbursed for that escrow item type or escrow category type, etc.
 * 
 * <p>Java class for ESCROW_ITEM_DETAIL complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ESCROW_ITEM_DETAIL">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="EscrowCollectedNumberOfMonthsCount" type="{http://www.mismo.org/residential/2009/schemas}MISMOCount" minOccurs="0"/>
 *         &lt;element name="EscrowItemType" type="{http://www.mismo.org/residential/2009/schemas}EscrowItemEnum" minOccurs="0"/>
 *         &lt;element name="EscrowItemTypeOtherDescription" type="{http://www.mismo.org/residential/2009/schemas}MISMOString" minOccurs="0"/>
 *         &lt;element name="EscrowMonthlyPaymentAmount" type="{http://www.mismo.org/residential/2009/schemas}MISMOAmount" minOccurs="0"/>
 *         &lt;element name="FeePaidToType" type="{http://www.mismo.org/residential/2009/schemas}FeePaidToEnum" minOccurs="0"/>
 *         &lt;element name="FeePaidToTypeOtherDescription" type="{http://www.mismo.org/residential/2009/schemas}FeePaidToTypeOtherDescriptionEnum" minOccurs="0"/>
 *         &lt;element name="IntegratedDisclosureSectionType" type="{http://www.mismo.org/residential/2009/schemas}IntegratedDisclosureSectionEnum" minOccurs="0"/>
 *         &lt;element name="RegulationZPointsAndFeesIndicator" type="{http://www.mismo.org/residential/2009/schemas}MISMOIndicator" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ESCROW_ITEM_DETAIL", propOrder = {
    "escrowCollectedNumberOfMonthsCount",
    "escrowItemType",
    "escrowItemTypeOtherDescription",
    "escrowMonthlyPaymentAmount",
    "feePaidToType",
    "feePaidToTypeOtherDescription",
    "integratedDisclosureSectionType",
    "regulationZPointsAndFeesIndicator"
})
public class ESCROWITEMDETAIL {

    @XmlElement(name = "EscrowCollectedNumberOfMonthsCount")
    protected MISMOCount escrowCollectedNumberOfMonthsCount;
    @XmlElement(name = "EscrowItemType")
    protected EscrowItemEnum escrowItemType;
    @XmlElement(name = "EscrowItemTypeOtherDescription")
    protected MISMOString escrowItemTypeOtherDescription;
    @XmlElement(name = "EscrowMonthlyPaymentAmount")
    protected MISMOAmount escrowMonthlyPaymentAmount;
    @XmlElement(name = "FeePaidToType")
    protected FeePaidToEnum feePaidToType;
    @XmlElement(name = "FeePaidToTypeOtherDescription")
    protected FeePaidToTypeOtherDescriptionEnum feePaidToTypeOtherDescription;
    @XmlElement(name = "IntegratedDisclosureSectionType")
    protected IntegratedDisclosureSectionEnum integratedDisclosureSectionType;
    @XmlElement(name = "RegulationZPointsAndFeesIndicator")
    protected MISMOIndicator regulationZPointsAndFeesIndicator;

    /**
     * Gets the value of the escrowCollectedNumberOfMonthsCount property.
     * 
     * @return
     *     possible object is
     *     {@link MISMOCount }
     *     
     */
    public MISMOCount getEscrowCollectedNumberOfMonthsCount() {
        return escrowCollectedNumberOfMonthsCount;
    }

    /**
     * Sets the value of the escrowCollectedNumberOfMonthsCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link MISMOCount }
     *     
     */
    public void setEscrowCollectedNumberOfMonthsCount(MISMOCount value) {
        this.escrowCollectedNumberOfMonthsCount = value;
    }

    /**
     * Gets the value of the escrowItemType property.
     * 
     * @return
     *     possible object is
     *     {@link EscrowItemEnum }
     *     
     */
    public EscrowItemEnum getEscrowItemType() {
        return escrowItemType;
    }

    /**
     * Sets the value of the escrowItemType property.
     * 
     * @param value
     *     allowed object is
     *     {@link EscrowItemEnum }
     *     
     */
    public void setEscrowItemType(EscrowItemEnum value) {
        this.escrowItemType = value;
    }

    /**
     * Gets the value of the escrowItemTypeOtherDescription property.
     * 
     * @return
     *     possible object is
     *     {@link MISMOString }
     *     
     */
    public MISMOString getEscrowItemTypeOtherDescription() {
        return escrowItemTypeOtherDescription;
    }

    /**
     * Sets the value of the escrowItemTypeOtherDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link MISMOString }
     *     
     */
    public void setEscrowItemTypeOtherDescription(MISMOString value) {
        this.escrowItemTypeOtherDescription = value;
    }

    /**
     * Gets the value of the escrowMonthlyPaymentAmount property.
     * 
     * @return
     *     possible object is
     *     {@link MISMOAmount }
     *     
     */
    public MISMOAmount getEscrowMonthlyPaymentAmount() {
        return escrowMonthlyPaymentAmount;
    }

    /**
     * Sets the value of the escrowMonthlyPaymentAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link MISMOAmount }
     *     
     */
    public void setEscrowMonthlyPaymentAmount(MISMOAmount value) {
        this.escrowMonthlyPaymentAmount = value;
    }

    /**
     * Gets the value of the feePaidToType property.
     * 
     * @return
     *     possible object is
     *     {@link FeePaidToEnum }
     *     
     */
    public FeePaidToEnum getFeePaidToType() {
        return feePaidToType;
    }

    /**
     * Sets the value of the feePaidToType property.
     * 
     * @param value
     *     allowed object is
     *     {@link FeePaidToEnum }
     *     
     */
    public void setFeePaidToType(FeePaidToEnum value) {
        this.feePaidToType = value;
    }

    /**
     * Gets the value of the feePaidToTypeOtherDescription property.
     * 
     * @return
     *     possible object is
     *     {@link FeePaidToTypeOtherDescriptionEnum }
     *     
     */
    public FeePaidToTypeOtherDescriptionEnum getFeePaidToTypeOtherDescription() {
        return feePaidToTypeOtherDescription;
    }

    /**
     * Sets the value of the feePaidToTypeOtherDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link FeePaidToTypeOtherDescriptionEnum }
     *     
     */
    public void setFeePaidToTypeOtherDescription(FeePaidToTypeOtherDescriptionEnum value) {
        this.feePaidToTypeOtherDescription = value;
    }

    /**
     * Gets the value of the integratedDisclosureSectionType property.
     * 
     * @return
     *     possible object is
     *     {@link IntegratedDisclosureSectionEnum }
     *     
     */
    public IntegratedDisclosureSectionEnum getIntegratedDisclosureSectionType() {
        return integratedDisclosureSectionType;
    }

    /**
     * Sets the value of the integratedDisclosureSectionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link IntegratedDisclosureSectionEnum }
     *     
     */
    public void setIntegratedDisclosureSectionType(IntegratedDisclosureSectionEnum value) {
        this.integratedDisclosureSectionType = value;
    }

    /**
     * Gets the value of the regulationZPointsAndFeesIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link MISMOIndicator }
     *     
     */
    public MISMOIndicator getRegulationZPointsAndFeesIndicator() {
        return regulationZPointsAndFeesIndicator;
    }

    /**
     * Sets the value of the regulationZPointsAndFeesIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link MISMOIndicator }
     *     
     */
    public void setRegulationZPointsAndFeesIndicator(MISMOIndicator value) {
        this.regulationZPointsAndFeesIndicator = value;
    }

}
