//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.01 at 06:02:48 PM IST 
//


package org.mismo.residential._2009.schemas;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Information about a specific escrow type that funds are collected and disbursed for.
 * 
 * <p>Java class for ESCROW_ITEM complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ESCROW_ITEM">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ESCROW_ITEM_DETAIL" type="{http://www.mismo.org/residential/2009/schemas}ESCROW_ITEM_DETAIL" minOccurs="0"/>
 *         &lt;element name="ESCROW_ITEM_PAYMENTS" type="{http://www.mismo.org/residential/2009/schemas}ESCROW_ITEM_PAYMENTS" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ESCROW_ITEM", propOrder = {
    "escrowitemdetail",
    "escrowitempayments"
})
public class ESCROWITEM {

    @XmlElement(name = "ESCROW_ITEM_DETAIL")
    protected ESCROWITEMDETAIL escrowitemdetail;
    @XmlElement(name = "ESCROW_ITEM_PAYMENTS")
    protected ESCROWITEMPAYMENTS escrowitempayments;

    /**
     * Gets the value of the escrowitemdetail property.
     * 
     * @return
     *     possible object is
     *     {@link ESCROWITEMDETAIL }
     *     
     */
    public ESCROWITEMDETAIL getESCROWITEMDETAIL() {
        return escrowitemdetail;
    }

    /**
     * Sets the value of the escrowitemdetail property.
     * 
     * @param value
     *     allowed object is
     *     {@link ESCROWITEMDETAIL }
     *     
     */
    public void setESCROWITEMDETAIL(ESCROWITEMDETAIL value) {
        this.escrowitemdetail = value;
    }

    /**
     * Gets the value of the escrowitempayments property.
     * 
     * @return
     *     possible object is
     *     {@link ESCROWITEMPAYMENTS }
     *     
     */
    public ESCROWITEMPAYMENTS getESCROWITEMPAYMENTS() {
        return escrowitempayments;
    }

    /**
     * Sets the value of the escrowitempayments property.
     * 
     * @param value
     *     allowed object is
     *     {@link ESCROWITEMPAYMENTS }
     *     
     */
    public void setESCROWITEMPAYMENTS(ESCROWITEMPAYMENTS value) {
        this.escrowitempayments = value;
    }

}
