//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.01 at 06:02:48 PM IST 
//


package org.mismo.residential._2009.schemas;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Information specific to funds collected through the loan payment and held to pay expenses such as taxes and insurance or funds held back after closing that are to be used for property improvements or repairs.
 * 
 * <p>Java class for ESCROW complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ESCROW">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ESCROW_DETAIL" type="{http://www.mismo.org/residential/2009/schemas}ESCROW_DETAIL" minOccurs="0"/>
 *         &lt;element name="ESCROW_ITEMS" type="{http://www.mismo.org/residential/2009/schemas}ESCROW_ITEMS" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ESCROW", propOrder = {
    "escrowdetail",
    "escrowitems"
})
public class ESCROW {

    @XmlElement(name = "ESCROW_DETAIL")
    protected ESCROWDETAIL escrowdetail;
    @XmlElement(name = "ESCROW_ITEMS")
    protected ESCROWITEMS escrowitems;

    /**
     * Gets the value of the escrowdetail property.
     * 
     * @return
     *     possible object is
     *     {@link ESCROWDETAIL }
     *     
     */
    public ESCROWDETAIL getESCROWDETAIL() {
        return escrowdetail;
    }

    /**
     * Sets the value of the escrowdetail property.
     * 
     * @param value
     *     allowed object is
     *     {@link ESCROWDETAIL }
     *     
     */
    public void setESCROWDETAIL(ESCROWDETAIL value) {
        this.escrowdetail = value;
    }

    /**
     * Gets the value of the escrowitems property.
     * 
     * @return
     *     possible object is
     *     {@link ESCROWITEMS }
     *     
     */
    public ESCROWITEMS getESCROWITEMS() {
        return escrowitems;
    }

    /**
     * Sets the value of the escrowitems property.
     * 
     * @param value
     *     allowed object is
     *     {@link ESCROWITEMS }
     *     
     */
    public void setESCROWITEMS(ESCROWITEMS value) {
        this.escrowitems = value;
    }

}
