//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.01 at 06:02:48 PM IST 
//


package org.mismo.residential._2009.schemas;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Information on the escrow item payment.
 * 
 * <p>Java class for ESCROW_ITEM_PAYMENT complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ESCROW_ITEM_PAYMENT">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="EscrowItemActualPaymentAmount" type="{http://www.mismo.org/residential/2009/schemas}MISMOAmount" minOccurs="0"/>
 *         &lt;element name="EscrowItemPaymentPaidByType" type="{http://www.mismo.org/residential/2009/schemas}EscrowItemPaymentPaidByEnum" minOccurs="0"/>
 *         &lt;element name="EscrowItemPaymentTimingType" type="{http://www.mismo.org/residential/2009/schemas}EscrowItemPaymentTimingEnum" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ESCROW_ITEM_PAYMENT", propOrder = {
    "escrowItemActualPaymentAmount",
    "escrowItemPaymentPaidByType",
    "escrowItemPaymentTimingType"
})
public class ESCROWITEMPAYMENT {

    @XmlElement(name = "EscrowItemActualPaymentAmount")
    protected MISMOAmount escrowItemActualPaymentAmount;
    @XmlElement(name = "EscrowItemPaymentPaidByType")
    protected EscrowItemPaymentPaidByEnum escrowItemPaymentPaidByType;
    @XmlElement(name = "EscrowItemPaymentTimingType")
    protected EscrowItemPaymentTimingEnum escrowItemPaymentTimingType;

    /**
     * Gets the value of the escrowItemActualPaymentAmount property.
     * 
     * @return
     *     possible object is
     *     {@link MISMOAmount }
     *     
     */
    public MISMOAmount getEscrowItemActualPaymentAmount() {
        return escrowItemActualPaymentAmount;
    }

    /**
     * Sets the value of the escrowItemActualPaymentAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link MISMOAmount }
     *     
     */
    public void setEscrowItemActualPaymentAmount(MISMOAmount value) {
        this.escrowItemActualPaymentAmount = value;
    }

    /**
     * Gets the value of the escrowItemPaymentPaidByType property.
     * 
     * @return
     *     possible object is
     *     {@link EscrowItemPaymentPaidByEnum }
     *     
     */
    public EscrowItemPaymentPaidByEnum getEscrowItemPaymentPaidByType() {
        return escrowItemPaymentPaidByType;
    }

    /**
     * Sets the value of the escrowItemPaymentPaidByType property.
     * 
     * @param value
     *     allowed object is
     *     {@link EscrowItemPaymentPaidByEnum }
     *     
     */
    public void setEscrowItemPaymentPaidByType(EscrowItemPaymentPaidByEnum value) {
        this.escrowItemPaymentPaidByType = value;
    }

    /**
     * Gets the value of the escrowItemPaymentTimingType property.
     * 
     * @return
     *     possible object is
     *     {@link EscrowItemPaymentTimingEnum }
     *     
     */
    public EscrowItemPaymentTimingEnum getEscrowItemPaymentTimingType() {
        return escrowItemPaymentTimingType;
    }

    /**
     * Sets the value of the escrowItemPaymentTimingType property.
     * 
     * @param value
     *     allowed object is
     *     {@link EscrowItemPaymentTimingEnum }
     *     
     */
    public void setEscrowItemPaymentTimingType(EscrowItemPaymentTimingEnum value) {
        this.escrowItemPaymentTimingType = value;
    }

}
