//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.01 at 06:02:48 PM IST 
//


package org.mismo.residential._2009.schemas;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Information about the type of property cost and whether or not the cost is escrowed.
 * 
 * <p>Java class for ESTIMATED_PROPERTY_COST_COMPONENT complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ESTIMATED_PROPERTY_COST_COMPONENT">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ProjectedPaymentEscrowedType" type="{http://www.mismo.org/residential/2009/schemas}ProjectedPaymentEscrowedEnum" minOccurs="0"/>
 *         &lt;element name="ProjectedPaymentEstimatedTaxesInsuranceAssessmentComponentType" type="{http://www.mismo.org/residential/2009/schemas}ProjectedPaymentEstimatedTaxesInsuranceAssessmentComponentEnum" minOccurs="0"/>
 *         &lt;element name="ProjectedPaymentEstimatedTaxesInsuranceAssessmentComponentTypeOtherDescription" type="{http://www.mismo.org/residential/2009/schemas}MISMOString" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ESTIMATED_PROPERTY_COST_COMPONENT", propOrder = {
    "projectedPaymentEscrowedType",
    "projectedPaymentEstimatedTaxesInsuranceAssessmentComponentType",
    "projectedPaymentEstimatedTaxesInsuranceAssessmentComponentTypeOtherDescription"
})
public class ESTIMATEDPROPERTYCOSTCOMPONENT {

    @XmlElement(name = "ProjectedPaymentEscrowedType")
    protected ProjectedPaymentEscrowedEnum projectedPaymentEscrowedType;
    @XmlElement(name = "ProjectedPaymentEstimatedTaxesInsuranceAssessmentComponentType")
    protected ProjectedPaymentEstimatedTaxesInsuranceAssessmentComponentEnum projectedPaymentEstimatedTaxesInsuranceAssessmentComponentType;
    @XmlElement(name = "ProjectedPaymentEstimatedTaxesInsuranceAssessmentComponentTypeOtherDescription")
    protected MISMOString projectedPaymentEstimatedTaxesInsuranceAssessmentComponentTypeOtherDescription;

    /**
     * Gets the value of the projectedPaymentEscrowedType property.
     * 
     * @return
     *     possible object is
     *     {@link ProjectedPaymentEscrowedEnum }
     *     
     */
    public ProjectedPaymentEscrowedEnum getProjectedPaymentEscrowedType() {
        return projectedPaymentEscrowedType;
    }

    /**
     * Sets the value of the projectedPaymentEscrowedType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProjectedPaymentEscrowedEnum }
     *     
     */
    public void setProjectedPaymentEscrowedType(ProjectedPaymentEscrowedEnum value) {
        this.projectedPaymentEscrowedType = value;
    }

    /**
     * Gets the value of the projectedPaymentEstimatedTaxesInsuranceAssessmentComponentType property.
     * 
     * @return
     *     possible object is
     *     {@link ProjectedPaymentEstimatedTaxesInsuranceAssessmentComponentEnum }
     *     
     */
    public ProjectedPaymentEstimatedTaxesInsuranceAssessmentComponentEnum getProjectedPaymentEstimatedTaxesInsuranceAssessmentComponentType() {
        return projectedPaymentEstimatedTaxesInsuranceAssessmentComponentType;
    }

    /**
     * Sets the value of the projectedPaymentEstimatedTaxesInsuranceAssessmentComponentType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProjectedPaymentEstimatedTaxesInsuranceAssessmentComponentEnum }
     *     
     */
    public void setProjectedPaymentEstimatedTaxesInsuranceAssessmentComponentType(ProjectedPaymentEstimatedTaxesInsuranceAssessmentComponentEnum value) {
        this.projectedPaymentEstimatedTaxesInsuranceAssessmentComponentType = value;
    }

    /**
     * Gets the value of the projectedPaymentEstimatedTaxesInsuranceAssessmentComponentTypeOtherDescription property.
     * 
     * @return
     *     possible object is
     *     {@link MISMOString }
     *     
     */
    public MISMOString getProjectedPaymentEstimatedTaxesInsuranceAssessmentComponentTypeOtherDescription() {
        return projectedPaymentEstimatedTaxesInsuranceAssessmentComponentTypeOtherDescription;
    }

    /**
     * Sets the value of the projectedPaymentEstimatedTaxesInsuranceAssessmentComponentTypeOtherDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link MISMOString }
     *     
     */
    public void setProjectedPaymentEstimatedTaxesInsuranceAssessmentComponentTypeOtherDescription(MISMOString value) {
        this.projectedPaymentEstimatedTaxesInsuranceAssessmentComponentTypeOtherDescription = value;
    }

}
