//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.01 at 06:02:48 PM IST 
//


package org.mismo.residential._2009.schemas;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Contains date and additional location detail regarding the signing event.
 * 
 * <p>Java class for EXECUTION_DETAIL complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EXECUTION_DETAIL">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ActualSignatureType" type="{http://www.mismo.org/residential/2009/schemas}ActualSignatureEnum" minOccurs="0"/>
 *         &lt;element name="ActualSignatureTypeOtherDescription" type="{http://www.mismo.org/residential/2009/schemas}MISMOString" minOccurs="0"/>
 *         &lt;element name="ExecutionDate" type="{http://www.mismo.org/residential/2009/schemas}MISMODate" minOccurs="0"/>
 *         &lt;element name="ExecutionDatetime" type="{http://www.mismo.org/residential/2009/schemas}MISMODatetime" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EXECUTION_DETAIL", propOrder = {
    "actualSignatureType",
    "actualSignatureTypeOtherDescription",
    "executionDate",
    "executionDatetime"
})
public class EXECUTIONDETAIL {

    @XmlElement(name = "ActualSignatureType")
    protected ActualSignatureEnum actualSignatureType;
    @XmlElement(name = "ActualSignatureTypeOtherDescription")
    protected MISMOString actualSignatureTypeOtherDescription;
    @XmlElement(name = "ExecutionDate")
    protected MISMODate executionDate;
    @XmlElement(name = "ExecutionDatetime")
    protected MISMODatetime executionDatetime;

    /**
     * Gets the value of the actualSignatureType property.
     * 
     * @return
     *     possible object is
     *     {@link ActualSignatureEnum }
     *     
     */
    public ActualSignatureEnum getActualSignatureType() {
        return actualSignatureType;
    }

    /**
     * Sets the value of the actualSignatureType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActualSignatureEnum }
     *     
     */
    public void setActualSignatureType(ActualSignatureEnum value) {
        this.actualSignatureType = value;
    }

    /**
     * Gets the value of the actualSignatureTypeOtherDescription property.
     * 
     * @return
     *     possible object is
     *     {@link MISMOString }
     *     
     */
    public MISMOString getActualSignatureTypeOtherDescription() {
        return actualSignatureTypeOtherDescription;
    }

    /**
     * Sets the value of the actualSignatureTypeOtherDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link MISMOString }
     *     
     */
    public void setActualSignatureTypeOtherDescription(MISMOString value) {
        this.actualSignatureTypeOtherDescription = value;
    }

    /**
     * Gets the value of the executionDate property.
     * 
     * @return
     *     possible object is
     *     {@link MISMODate }
     *     
     */
    public MISMODate getExecutionDate() {
        return executionDate;
    }

    /**
     * Sets the value of the executionDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link MISMODate }
     *     
     */
    public void setExecutionDate(MISMODate value) {
        this.executionDate = value;
    }

    /**
     * Gets the value of the executionDatetime property.
     * 
     * @return
     *     possible object is
     *     {@link MISMODatetime }
     *     
     */
    public MISMODatetime getExecutionDatetime() {
        return executionDatetime;
    }

    /**
     * Sets the value of the executionDatetime property.
     * 
     * @param value
     *     allowed object is
     *     {@link MISMODatetime }
     *     
     */
    public void setExecutionDatetime(MISMODatetime value) {
        this.executionDatetime = value;
    }

}
