//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.01 at 06:02:48 PM IST 
//


package org.mismo.residential._2009.schemas;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FEE_INFORMATION complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FEE_INFORMATION">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="FEES" type="{http://www.mismo.org/residential/2009/schemas}FEES"/>
 *         &lt;element name="FEES_SUMMARY" type="{http://www.mismo.org/residential/2009/schemas}FEES_SUMMARY" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FEE_INFORMATION", propOrder = {
    "fees",
    "feessummary"
})
public class FEEINFORMATION {

    @XmlElement(name = "FEES", required = true)
    protected FEES fees;
    @XmlElement(name = "FEES_SUMMARY")
    protected FEESSUMMARY feessummary;

    /**
     * Gets the value of the fees property.
     * 
     * @return
     *     possible object is
     *     {@link FEES }
     *     
     */
    public FEES getFEES() {
        return fees;
    }

    /**
     * Sets the value of the fees property.
     * 
     * @param value
     *     allowed object is
     *     {@link FEES }
     *     
     */
    public void setFEES(FEES value) {
        this.fees = value;
    }

    /**
     * Gets the value of the feessummary property.
     * 
     * @return
     *     possible object is
     *     {@link FEESSUMMARY }
     *     
     */
    public FEESSUMMARY getFEESSUMMARY() {
        return feessummary;
    }

    /**
     * Sets the value of the feessummary property.
     * 
     * @param value
     *     allowed object is
     *     {@link FEESSUMMARY }
     *     
     */
    public void setFEESSUMMARY(FEESSUMMARY value) {
        this.feessummary = value;
    }

}
