//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.01 at 06:02:48 PM IST 
//


package org.mismo.residential._2009.schemas;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FeePaidToTypeOtherDescriptionBase.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="FeePaidToTypeOtherDescriptionBase">
 *   &lt;restriction base="{http://www.mismo.org/residential/2009/schemas}MISMOEnum_Base">
 *     &lt;enumeration value="BrokerAffiliate"/>
 *     &lt;enumeration value="LenderAffiliate"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "FeePaidToTypeOtherDescriptionBase")
@XmlEnum
public enum FeePaidToTypeOtherDescriptionBase {


    /**
     * Fee is being paid to a third party provider who is an affiliate of the Mortgage Broker.
     * 
     */
    @XmlEnumValue("BrokerAffiliate")
    BROKER_AFFILIATE("BrokerAffiliate"),

    /**
     * Fee is being paid to a third party provider who is an affiliate of the Lender or Creditor.
     * 
     */
    @XmlEnumValue("LenderAffiliate")
    LENDER_AFFILIATE("LenderAffiliate");
    private final String value;

    FeePaidToTypeOtherDescriptionBase(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static FeePaidToTypeOtherDescriptionBase fromValue(String v) {
        for (FeePaidToTypeOtherDescriptionBase c: FeePaidToTypeOtherDescriptionBase.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
