//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.01 at 06:02:48 PM IST 
//


package org.mismo.residential._2009.schemas;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FEE_PAYMENT complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FEE_PAYMENT">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="FeeActualPaymentAmount" type="{http://www.mismo.org/residential/2009/schemas}MISMOAmount" minOccurs="0"/>
 *         &lt;element name="FeePaymentPaidByType" type="{http://www.mismo.org/residential/2009/schemas}FeePaymentPaidByEnum" minOccurs="0"/>
 *         &lt;element name="FeePaymentPaidOutsideOfClosingIndicator" type="{http://www.mismo.org/residential/2009/schemas}MISMOIndicator" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FEE_PAYMENT", propOrder = {
    "feeActualPaymentAmount",
    "feePaymentPaidByType",
    "feePaymentPaidOutsideOfClosingIndicator"
})
public class FEEPAYMENT {

    @XmlElement(name = "FeeActualPaymentAmount")
    protected MISMOAmount feeActualPaymentAmount;
    @XmlElement(name = "FeePaymentPaidByType")
    protected FeePaymentPaidByEnum feePaymentPaidByType;
    @XmlElement(name = "FeePaymentPaidOutsideOfClosingIndicator")
    protected MISMOIndicator feePaymentPaidOutsideOfClosingIndicator;

    /**
     * Gets the value of the feeActualPaymentAmount property.
     * 
     * @return
     *     possible object is
     *     {@link MISMOAmount }
     *     
     */
    public MISMOAmount getFeeActualPaymentAmount() {
        return feeActualPaymentAmount;
    }

    /**
     * Sets the value of the feeActualPaymentAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link MISMOAmount }
     *     
     */
    public void setFeeActualPaymentAmount(MISMOAmount value) {
        this.feeActualPaymentAmount = value;
    }

    /**
     * Gets the value of the feePaymentPaidByType property.
     * 
     * @return
     *     possible object is
     *     {@link FeePaymentPaidByEnum }
     *     
     */
    public FeePaymentPaidByEnum getFeePaymentPaidByType() {
        return feePaymentPaidByType;
    }

    /**
     * Sets the value of the feePaymentPaidByType property.
     * 
     * @param value
     *     allowed object is
     *     {@link FeePaymentPaidByEnum }
     *     
     */
    public void setFeePaymentPaidByType(FeePaymentPaidByEnum value) {
        this.feePaymentPaidByType = value;
    }

    /**
     * Gets the value of the feePaymentPaidOutsideOfClosingIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link MISMOIndicator }
     *     
     */
    public MISMOIndicator getFeePaymentPaidOutsideOfClosingIndicator() {
        return feePaymentPaidOutsideOfClosingIndicator;
    }

    /**
     * Sets the value of the feePaymentPaidOutsideOfClosingIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link MISMOIndicator }
     *     
     */
    public void setFeePaymentPaidOutsideOfClosingIndicator(MISMOIndicator value) {
        this.feePaymentPaidOutsideOfClosingIndicator = value;
    }

}
