//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.01 at 06:02:48 PM IST 
//


package org.mismo.residential._2009.schemas;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FEES_SUMMARY complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FEES_SUMMARY">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="FEE_SUMMARY_DETAIL" type="{http://www.mismo.org/residential/2009/schemas}FEE_SUMMARY_DETAIL"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FEES_SUMMARY", propOrder = {
    "feesummarydetail"
})
public class FEESSUMMARY {

    @XmlElement(name = "FEE_SUMMARY_DETAIL", required = true)
    protected FEESUMMARYDETAIL feesummarydetail;

    /**
     * Gets the value of the feesummarydetail property.
     * 
     * @return
     *     possible object is
     *     {@link FEESUMMARYDETAIL }
     *     
     */
    public FEESUMMARYDETAIL getFEESUMMARYDETAIL() {
        return feesummarydetail;
    }

    /**
     * Sets the value of the feesummarydetail property.
     * 
     * @param value
     *     allowed object is
     *     {@link FEESUMMARYDETAIL }
     *     
     */
    public void setFEESUMMARYDETAIL(FEESUMMARYDETAIL value) {
        this.feesummarydetail = value;
    }

}
