//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.01 at 06:02:48 PM IST 
//


package org.mismo.residential._2009.schemas;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Information related to one or more determinations of the transaction as a high cost or higher priced mortgage. Holds all occurrences of HIGH_COST_MORTGAGE.
 * 
 * <p>Java class for HIGH_COST_MORTGAGES complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="HIGH_COST_MORTGAGES">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="HIGH_COST_MORTGAGE" type="{http://www.mismo.org/residential/2009/schemas}HIGH_COST_MORTGAGE"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HIGH_COST_MORTGAGES", propOrder = {
    "highcostmortgage"
})
public class HIGHCOSTMORTGAGES {

    @XmlElement(name = "HIGH_COST_MORTGAGE", required = true)
    protected HIGHCOSTMORTGAGE highcostmortgage;

    /**
     * Gets the value of the highcostmortgage property.
     * 
     * @return
     *     possible object is
     *     {@link HIGHCOSTMORTGAGE }
     *     
     */
    public HIGHCOSTMORTGAGE getHIGHCOSTMORTGAGE() {
        return highcostmortgage;
    }

    /**
     * Sets the value of the highcostmortgage property.
     * 
     * @param value
     *     allowed object is
     *     {@link HIGHCOSTMORTGAGE }
     *     
     */
    public void setHIGHCOSTMORTGAGE(HIGHCOSTMORTGAGE value) {
        this.highcostmortgage = value;
    }

}
