//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.01 at 06:02:48 PM IST 
//


package org.mismo.residential._2009.schemas;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Information related to a determination of the transaction as a high cost or higher priced mortgage.
 * 
 * <p>Java class for HIGH_COST_MORTGAGE complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="HIGH_COST_MORTGAGE">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AveragePrimeOfferRatePercent" type="{http://www.mismo.org/residential/2009/schemas}MISMOPercent" minOccurs="0"/>
 *         &lt;element name="RegulationZExcludedBonaFideDiscountPointsIndicator" type="{http://www.mismo.org/residential/2009/schemas}MISMOIndicator" minOccurs="0"/>
 *         &lt;element name="RegulationZExcludedBonaFideDiscountPointsPercent" type="{http://www.mismo.org/residential/2009/schemas}MISMOPercent" minOccurs="0"/>
 *         &lt;element name="RegulationZTotalAffiliateFeesAmount" type="{http://www.mismo.org/residential/2009/schemas}MISMOAmount" minOccurs="0"/>
 *         &lt;element name="RegulationZTotalLoanAmount" type="{http://www.mismo.org/residential/2009/schemas}MISMOAmount" minOccurs="0"/>
 *         &lt;element name="RegulationZTotalPointsAndFeesAmount" type="{http://www.mismo.org/residential/2009/schemas}MISMOAmount" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HIGH_COST_MORTGAGE", propOrder = {
    "averagePrimeOfferRatePercent",
    "regulationZExcludedBonaFideDiscountPointsIndicator",
    "regulationZExcludedBonaFideDiscountPointsPercent",
    "regulationZTotalAffiliateFeesAmount",
    "regulationZTotalLoanAmount",
    "regulationZTotalPointsAndFeesAmount"
})
public class HIGHCOSTMORTGAGE {

    @XmlElement(name = "AveragePrimeOfferRatePercent")
    protected MISMOPercent averagePrimeOfferRatePercent;
    @XmlElement(name = "RegulationZExcludedBonaFideDiscountPointsIndicator")
    protected MISMOIndicator regulationZExcludedBonaFideDiscountPointsIndicator;
    @XmlElement(name = "RegulationZExcludedBonaFideDiscountPointsPercent")
    protected MISMOPercent regulationZExcludedBonaFideDiscountPointsPercent;
    @XmlElement(name = "RegulationZTotalAffiliateFeesAmount")
    protected MISMOAmount regulationZTotalAffiliateFeesAmount;
    @XmlElement(name = "RegulationZTotalLoanAmount")
    protected MISMOAmount regulationZTotalLoanAmount;
    @XmlElement(name = "RegulationZTotalPointsAndFeesAmount")
    protected MISMOAmount regulationZTotalPointsAndFeesAmount;

    /**
     * Gets the value of the averagePrimeOfferRatePercent property.
     * 
     * @return
     *     possible object is
     *     {@link MISMOPercent }
     *     
     */
    public MISMOPercent getAveragePrimeOfferRatePercent() {
        return averagePrimeOfferRatePercent;
    }

    /**
     * Sets the value of the averagePrimeOfferRatePercent property.
     * 
     * @param value
     *     allowed object is
     *     {@link MISMOPercent }
     *     
     */
    public void setAveragePrimeOfferRatePercent(MISMOPercent value) {
        this.averagePrimeOfferRatePercent = value;
    }

    /**
     * Gets the value of the regulationZExcludedBonaFideDiscountPointsIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link MISMOIndicator }
     *     
     */
    public MISMOIndicator getRegulationZExcludedBonaFideDiscountPointsIndicator() {
        return regulationZExcludedBonaFideDiscountPointsIndicator;
    }

    /**
     * Sets the value of the regulationZExcludedBonaFideDiscountPointsIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link MISMOIndicator }
     *     
     */
    public void setRegulationZExcludedBonaFideDiscountPointsIndicator(MISMOIndicator value) {
        this.regulationZExcludedBonaFideDiscountPointsIndicator = value;
    }

    /**
     * Gets the value of the regulationZExcludedBonaFideDiscountPointsPercent property.
     * 
     * @return
     *     possible object is
     *     {@link MISMOPercent }
     *     
     */
    public MISMOPercent getRegulationZExcludedBonaFideDiscountPointsPercent() {
        return regulationZExcludedBonaFideDiscountPointsPercent;
    }

    /**
     * Sets the value of the regulationZExcludedBonaFideDiscountPointsPercent property.
     * 
     * @param value
     *     allowed object is
     *     {@link MISMOPercent }
     *     
     */
    public void setRegulationZExcludedBonaFideDiscountPointsPercent(MISMOPercent value) {
        this.regulationZExcludedBonaFideDiscountPointsPercent = value;
    }

    /**
     * Gets the value of the regulationZTotalAffiliateFeesAmount property.
     * 
     * @return
     *     possible object is
     *     {@link MISMOAmount }
     *     
     */
    public MISMOAmount getRegulationZTotalAffiliateFeesAmount() {
        return regulationZTotalAffiliateFeesAmount;
    }

    /**
     * Sets the value of the regulationZTotalAffiliateFeesAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link MISMOAmount }
     *     
     */
    public void setRegulationZTotalAffiliateFeesAmount(MISMOAmount value) {
        this.regulationZTotalAffiliateFeesAmount = value;
    }

    /**
     * Gets the value of the regulationZTotalLoanAmount property.
     * 
     * @return
     *     possible object is
     *     {@link MISMOAmount }
     *     
     */
    public MISMOAmount getRegulationZTotalLoanAmount() {
        return regulationZTotalLoanAmount;
    }

    /**
     * Sets the value of the regulationZTotalLoanAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link MISMOAmount }
     *     
     */
    public void setRegulationZTotalLoanAmount(MISMOAmount value) {
        this.regulationZTotalLoanAmount = value;
    }

    /**
     * Gets the value of the regulationZTotalPointsAndFeesAmount property.
     * 
     * @return
     *     possible object is
     *     {@link MISMOAmount }
     *     
     */
    public MISMOAmount getRegulationZTotalPointsAndFeesAmount() {
        return regulationZTotalPointsAndFeesAmount;
    }

    /**
     * Sets the value of the regulationZTotalPointsAndFeesAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link MISMOAmount }
     *     
     */
    public void setRegulationZTotalPointsAndFeesAmount(MISMOAmount value) {
        this.regulationZTotalPointsAndFeesAmount = value;
    }

}
