//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.01 at 06:02:48 PM IST 
//


package org.mismo.residential._2009.schemas;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for INDEX_RULES complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="INDEX_RULES">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="INDEX_RULE" type="{http://www.mismo.org/residential/2009/schemas}INDEX_RULE" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "INDEX_RULES", propOrder = {
    "indexrule"
})
public class INDEXRULES {

    @XmlElement(name = "INDEX_RULE")
    protected INDEXRULE indexrule;

    /**
     * Gets the value of the indexrule property.
     * 
     * @return
     *     possible object is
     *     {@link INDEXRULE }
     *     
     */
    public INDEXRULE getINDEXRULE() {
        return indexrule;
    }

    /**
     * Sets the value of the indexrule property.
     * 
     * @param value
     *     allowed object is
     *     {@link INDEXRULE }
     *     
     */
    public void setINDEXRULE(INDEXRULE value) {
        this.indexrule = value;
    }

}
