//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.01 at 06:02:48 PM IST 
//


package org.mismo.residential._2009.schemas;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for IndexBase.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="IndexBase">
 *   &lt;restriction base="{http://www.mismo.org/residential/2009/schemas}MISMOEnum_Base">
 *     &lt;enumeration value="BankPrimeLoan"/>
 *     &lt;enumeration value="CertificateOfDepositIndex"/>
 *     &lt;enumeration value="ConstantMaturityTreasury"/>
 *     &lt;enumeration value="CostOfSavingsIndex"/>
 *     &lt;enumeration value="EleventhDistrictCostOfFundsIndex"/>
 *     &lt;enumeration value="LIBOR"/>
 *     &lt;enumeration value="Other"/>
 *     &lt;enumeration value="TreasuryBill"/>
 *     &lt;enumeration value="TwelveMonthTreasuryAverage"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "IndexBase")
@XmlEnum
public enum IndexBase {


    /**
     * Often referred to as Prime Rate
     * 
     */
    @XmlEnumValue("BankPrimeLoan")
    BANK_PRIME_LOAN("BankPrimeLoan"),

    /**
     * Often referred to as CODI
     * 
     */
    @XmlEnumValue("CertificateOfDepositIndex")
    CERTIFICATE_OF_DEPOSIT_INDEX("CertificateOfDepositIndex"),

    /**
     * Often referred to as CMT
     * 
     */
    @XmlEnumValue("ConstantMaturityTreasury")
    CONSTANT_MATURITY_TREASURY("ConstantMaturityTreasury"),

    /**
     * Often referred to as COSI
     * 
     */
    @XmlEnumValue("CostOfSavingsIndex")
    COST_OF_SAVINGS_INDEX("CostOfSavingsIndex"),

    /**
     * Often referred to as COFI
     * 
     */
    @XmlEnumValue("EleventhDistrictCostOfFundsIndex")
    ELEVENTH_DISTRICT_COST_OF_FUNDS_INDEX("EleventhDistrictCostOfFundsIndex"),

    /**
     * London Interbank Offered Rate
     * 
     */
    LIBOR("LIBOR"),
    @XmlEnumValue("Other")
    OTHER("Other"),

    /**
     * Often referred to as T-Bill
     * 
     */
    @XmlEnumValue("TreasuryBill")
    TREASURY_BILL("TreasuryBill"),

    /**
     * Often referred to as MTA
     * 
     */
    @XmlEnumValue("TwelveMonthTreasuryAverage")
    TWELVE_MONTH_TREASURY_AVERAGE("TwelveMonthTreasuryAverage");
    private final String value;

    IndexBase(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static IndexBase fromValue(String v) {
        for (IndexBase c: IndexBase.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
