//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.01 at 06:02:48 PM IST 
//


package org.mismo.residential._2009.schemas;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Data that describes the rules that that apply to interest rate adjustments in effect for the entire life of the loan or for a single unique occurrence such as a first rate adjustment. In general the element are usually known at the time of closing.
 * 
 * <p>Java class for INTEREST_RATE_LIFETIME_ADJUSTMENT_RULE complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="INTEREST_RATE_LIFETIME_ADJUSTMENT_RULE">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CeilingRatePercent" type="{http://www.mismo.org/residential/2009/schemas}MISMOPercent" minOccurs="0"/>
 *         &lt;element name="CeilingRatePercentEarliestEffectiveMonthsCount" type="{http://www.mismo.org/residential/2009/schemas}MISMOCount" minOccurs="0"/>
 *         &lt;element name="FirstRateChangeMonthsCount" type="{http://www.mismo.org/residential/2009/schemas}MISMOCount" minOccurs="0"/>
 *         &lt;element name="FloorRatePercent" type="{http://www.mismo.org/residential/2009/schemas}MISMOPercent" minOccurs="0"/>
 *         &lt;element name="MarginRatePercent" type="{http://www.mismo.org/residential/2009/schemas}MISMOPercent" minOccurs="0"/>
 *         &lt;element name="EXTENSION" type="{http://www.mismo.org/residential/2009/schemas}INTEREST_RATE_LIFETIME_ADJUSTMENT_RULE_EXTENSION" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "INTEREST_RATE_LIFETIME_ADJUSTMENT_RULE", propOrder = {
    "ceilingRatePercent",
    "ceilingRatePercentEarliestEffectiveMonthsCount",
    "firstRateChangeMonthsCount",
    "floorRatePercent",
    "marginRatePercent",
    "extension"
})
public class INTERESTRATELIFETIMEADJUSTMENTRULE {

    @XmlElement(name = "CeilingRatePercent")
    protected MISMOPercent ceilingRatePercent;
    @XmlElement(name = "CeilingRatePercentEarliestEffectiveMonthsCount")
    protected MISMOCount ceilingRatePercentEarliestEffectiveMonthsCount;
    @XmlElement(name = "FirstRateChangeMonthsCount")
    protected MISMOCount firstRateChangeMonthsCount;
    @XmlElement(name = "FloorRatePercent")
    protected MISMOPercent floorRatePercent;
    @XmlElement(name = "MarginRatePercent")
    protected MISMOPercent marginRatePercent;
    @XmlElement(name = "EXTENSION")
    protected INTERESTRATELIFETIMEADJUSTMENTRULEEXTENSION extension;

    /**
     * Gets the value of the ceilingRatePercent property.
     * 
     * @return
     *     possible object is
     *     {@link MISMOPercent }
     *     
     */
    public MISMOPercent getCeilingRatePercent() {
        return ceilingRatePercent;
    }

    /**
     * Sets the value of the ceilingRatePercent property.
     * 
     * @param value
     *     allowed object is
     *     {@link MISMOPercent }
     *     
     */
    public void setCeilingRatePercent(MISMOPercent value) {
        this.ceilingRatePercent = value;
    }

    /**
     * Gets the value of the ceilingRatePercentEarliestEffectiveMonthsCount property.
     * 
     * @return
     *     possible object is
     *     {@link MISMOCount }
     *     
     */
    public MISMOCount getCeilingRatePercentEarliestEffectiveMonthsCount() {
        return ceilingRatePercentEarliestEffectiveMonthsCount;
    }

    /**
     * Sets the value of the ceilingRatePercentEarliestEffectiveMonthsCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link MISMOCount }
     *     
     */
    public void setCeilingRatePercentEarliestEffectiveMonthsCount(MISMOCount value) {
        this.ceilingRatePercentEarliestEffectiveMonthsCount = value;
    }

    /**
     * Gets the value of the firstRateChangeMonthsCount property.
     * 
     * @return
     *     possible object is
     *     {@link MISMOCount }
     *     
     */
    public MISMOCount getFirstRateChangeMonthsCount() {
        return firstRateChangeMonthsCount;
    }

    /**
     * Sets the value of the firstRateChangeMonthsCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link MISMOCount }
     *     
     */
    public void setFirstRateChangeMonthsCount(MISMOCount value) {
        this.firstRateChangeMonthsCount = value;
    }

    /**
     * Gets the value of the floorRatePercent property.
     * 
     * @return
     *     possible object is
     *     {@link MISMOPercent }
     *     
     */
    public MISMOPercent getFloorRatePercent() {
        return floorRatePercent;
    }

    /**
     * Sets the value of the floorRatePercent property.
     * 
     * @param value
     *     allowed object is
     *     {@link MISMOPercent }
     *     
     */
    public void setFloorRatePercent(MISMOPercent value) {
        this.floorRatePercent = value;
    }

    /**
     * Gets the value of the marginRatePercent property.
     * 
     * @return
     *     possible object is
     *     {@link MISMOPercent }
     *     
     */
    public MISMOPercent getMarginRatePercent() {
        return marginRatePercent;
    }

    /**
     * Sets the value of the marginRatePercent property.
     * 
     * @param value
     *     allowed object is
     *     {@link MISMOPercent }
     *     
     */
    public void setMarginRatePercent(MISMOPercent value) {
        this.marginRatePercent = value;
    }

    /**
     * Gets the value of the extension property.
     * 
     * @return
     *     possible object is
     *     {@link INTERESTRATELIFETIMEADJUSTMENTRULEEXTENSION }
     *     
     */
    public INTERESTRATELIFETIMEADJUSTMENTRULEEXTENSION getEXTENSION() {
        return extension;
    }

    /**
     * Sets the value of the extension property.
     * 
     * @param value
     *     allowed object is
     *     {@link INTERESTRATELIFETIMEADJUSTMENTRULEEXTENSION }
     *     
     */
    public void setEXTENSION(INTERESTRATELIFETIMEADJUSTMENTRULEEXTENSION value) {
        this.extension = value;
    }

}
