//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.01 at 06:02:48 PM IST 
//


package org.mismo.residential._2009.schemas;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Additional information specific to the integrated disclosure documents.
 * 
 * <p>Java class for INTEGRATED_DISCLOSURE_DETAIL complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="INTEGRATED_DISCLOSURE_DETAIL">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="FirstYearTotalEscrowPaymentAmount" type="{http://www.mismo.org/residential/2009/schemas}MISMOAmount" minOccurs="0"/>
 *         &lt;element name="FirstYearTotalEscrowPaymentDescription" type="{http://www.mismo.org/residential/2009/schemas}MISMOString" minOccurs="0"/>
 *         &lt;element name="FirstYearTotalNonEscrowPaymentAmount" type="{http://www.mismo.org/residential/2009/schemas}MISMOAmount" minOccurs="0"/>
 *         &lt;element name="FirstYearTotalNonEscrowPaymentDescription" type="{http://www.mismo.org/residential/2009/schemas}MISMOString" minOccurs="0"/>
 *         &lt;element name="IntegratedDisclosureHomeEquityLoanIndicator" type="{http://www.mismo.org/residential/2009/schemas}MISMOIndicator" minOccurs="0"/>
 *         &lt;element name="IntegratedDisclosureIssuedDate" type="{http://www.mismo.org/residential/2009/schemas}MISMODate"/>
 *         &lt;element name="IntegratedDisclosureLoanProductDescription" type="{http://www.mismo.org/residential/2009/schemas}MISMOString" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "INTEGRATED_DISCLOSURE_DETAIL", propOrder = {
    "firstYearTotalEscrowPaymentAmount",
    "firstYearTotalEscrowPaymentDescription",
    "firstYearTotalNonEscrowPaymentAmount",
    "firstYearTotalNonEscrowPaymentDescription",
    "integratedDisclosureHomeEquityLoanIndicator",
    "integratedDisclosureIssuedDate",
    "integratedDisclosureLoanProductDescription"
})
public class INTEGRATEDDISCLOSUREDETAIL {

    @XmlElement(name = "FirstYearTotalEscrowPaymentAmount")
    protected MISMOAmount firstYearTotalEscrowPaymentAmount;
    @XmlElement(name = "FirstYearTotalEscrowPaymentDescription")
    protected MISMOString firstYearTotalEscrowPaymentDescription;
    @XmlElement(name = "FirstYearTotalNonEscrowPaymentAmount")
    protected MISMOAmount firstYearTotalNonEscrowPaymentAmount;
    @XmlElement(name = "FirstYearTotalNonEscrowPaymentDescription")
    protected MISMOString firstYearTotalNonEscrowPaymentDescription;
    @XmlElement(name = "IntegratedDisclosureHomeEquityLoanIndicator")
    protected MISMOIndicator integratedDisclosureHomeEquityLoanIndicator;
    @XmlElement(name = "IntegratedDisclosureIssuedDate", required = true)
    protected MISMODate integratedDisclosureIssuedDate;
    @XmlElement(name = "IntegratedDisclosureLoanProductDescription")
    protected MISMOString integratedDisclosureLoanProductDescription;

    /**
     * Gets the value of the firstYearTotalEscrowPaymentAmount property.
     * 
     * @return
     *     possible object is
     *     {@link MISMOAmount }
     *     
     */
    public MISMOAmount getFirstYearTotalEscrowPaymentAmount() {
        return firstYearTotalEscrowPaymentAmount;
    }

    /**
     * Sets the value of the firstYearTotalEscrowPaymentAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link MISMOAmount }
     *     
     */
    public void setFirstYearTotalEscrowPaymentAmount(MISMOAmount value) {
        this.firstYearTotalEscrowPaymentAmount = value;
    }

    /**
     * Gets the value of the firstYearTotalEscrowPaymentDescription property.
     * 
     * @return
     *     possible object is
     *     {@link MISMOString }
     *     
     */
    public MISMOString getFirstYearTotalEscrowPaymentDescription() {
        return firstYearTotalEscrowPaymentDescription;
    }

    /**
     * Sets the value of the firstYearTotalEscrowPaymentDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link MISMOString }
     *     
     */
    public void setFirstYearTotalEscrowPaymentDescription(MISMOString value) {
        this.firstYearTotalEscrowPaymentDescription = value;
    }

    /**
     * Gets the value of the firstYearTotalNonEscrowPaymentAmount property.
     * 
     * @return
     *     possible object is
     *     {@link MISMOAmount }
     *     
     */
    public MISMOAmount getFirstYearTotalNonEscrowPaymentAmount() {
        return firstYearTotalNonEscrowPaymentAmount;
    }

    /**
     * Sets the value of the firstYearTotalNonEscrowPaymentAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link MISMOAmount }
     *     
     */
    public void setFirstYearTotalNonEscrowPaymentAmount(MISMOAmount value) {
        this.firstYearTotalNonEscrowPaymentAmount = value;
    }

    /**
     * Gets the value of the firstYearTotalNonEscrowPaymentDescription property.
     * 
     * @return
     *     possible object is
     *     {@link MISMOString }
     *     
     */
    public MISMOString getFirstYearTotalNonEscrowPaymentDescription() {
        return firstYearTotalNonEscrowPaymentDescription;
    }

    /**
     * Sets the value of the firstYearTotalNonEscrowPaymentDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link MISMOString }
     *     
     */
    public void setFirstYearTotalNonEscrowPaymentDescription(MISMOString value) {
        this.firstYearTotalNonEscrowPaymentDescription = value;
    }

    /**
     * Gets the value of the integratedDisclosureHomeEquityLoanIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link MISMOIndicator }
     *     
     */
    public MISMOIndicator getIntegratedDisclosureHomeEquityLoanIndicator() {
        return integratedDisclosureHomeEquityLoanIndicator;
    }

    /**
     * Sets the value of the integratedDisclosureHomeEquityLoanIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link MISMOIndicator }
     *     
     */
    public void setIntegratedDisclosureHomeEquityLoanIndicator(MISMOIndicator value) {
        this.integratedDisclosureHomeEquityLoanIndicator = value;
    }

    /**
     * Gets the value of the integratedDisclosureIssuedDate property.
     * 
     * @return
     *     possible object is
     *     {@link MISMODate }
     *     
     */
    public MISMODate getIntegratedDisclosureIssuedDate() {
        return integratedDisclosureIssuedDate;
    }

    /**
     * Sets the value of the integratedDisclosureIssuedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link MISMODate }
     *     
     */
    public void setIntegratedDisclosureIssuedDate(MISMODate value) {
        this.integratedDisclosureIssuedDate = value;
    }

    /**
     * Gets the value of the integratedDisclosureLoanProductDescription property.
     * 
     * @return
     *     possible object is
     *     {@link MISMOString }
     *     
     */
    public MISMOString getIntegratedDisclosureLoanProductDescription() {
        return integratedDisclosureLoanProductDescription;
    }

    /**
     * Sets the value of the integratedDisclosureLoanProductDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link MISMOString }
     *     
     */
    public void setIntegratedDisclosureLoanProductDescription(MISMOString value) {
        this.integratedDisclosureLoanProductDescription = value;
    }

}
