//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.01 at 06:02:48 PM IST 
//


package org.mismo.residential._2009.schemas;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Information regarding the amount, timing and responsible party for a specific Integrated Disclosure Subsection Type.
 * 
 * <p>Java class for INTEGRATED_DISCLOSURE_SUBSECTION_PAYMENT complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="INTEGRATED_DISCLOSURE_SUBSECTION_PAYMENT">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="IntegratedDisclosureSubsectionPaidByType" type="{http://www.mismo.org/residential/2009/schemas}IntegratedDisclosureSubsectionPaidByEnum" minOccurs="0"/>
 *         &lt;element name="IntegratedDisclosureSubsectionPaymentAmount" type="{http://www.mismo.org/residential/2009/schemas}MISMOAmount" minOccurs="0"/>
 *         &lt;element name="IntegratedDisclosureSubsectionPaymentTimingType" type="{http://www.mismo.org/residential/2009/schemas}IntegratedDisclosureSubsectionPaymentTimingEnum" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "INTEGRATED_DISCLOSURE_SUBSECTION_PAYMENT", propOrder = {
    "integratedDisclosureSubsectionPaidByType",
    "integratedDisclosureSubsectionPaymentAmount",
    "integratedDisclosureSubsectionPaymentTimingType"
})
public class INTEGRATEDDISCLOSURESUBSECTIONPAYMENT {

    @XmlElement(name = "IntegratedDisclosureSubsectionPaidByType")
    protected IntegratedDisclosureSubsectionPaidByEnum integratedDisclosureSubsectionPaidByType;
    @XmlElement(name = "IntegratedDisclosureSubsectionPaymentAmount")
    protected MISMOAmount integratedDisclosureSubsectionPaymentAmount;
    @XmlElement(name = "IntegratedDisclosureSubsectionPaymentTimingType")
    protected IntegratedDisclosureSubsectionPaymentTimingEnum integratedDisclosureSubsectionPaymentTimingType;

    /**
     * Gets the value of the integratedDisclosureSubsectionPaidByType property.
     * 
     * @return
     *     possible object is
     *     {@link IntegratedDisclosureSubsectionPaidByEnum }
     *     
     */
    public IntegratedDisclosureSubsectionPaidByEnum getIntegratedDisclosureSubsectionPaidByType() {
        return integratedDisclosureSubsectionPaidByType;
    }

    /**
     * Sets the value of the integratedDisclosureSubsectionPaidByType property.
     * 
     * @param value
     *     allowed object is
     *     {@link IntegratedDisclosureSubsectionPaidByEnum }
     *     
     */
    public void setIntegratedDisclosureSubsectionPaidByType(IntegratedDisclosureSubsectionPaidByEnum value) {
        this.integratedDisclosureSubsectionPaidByType = value;
    }

    /**
     * Gets the value of the integratedDisclosureSubsectionPaymentAmount property.
     * 
     * @return
     *     possible object is
     *     {@link MISMOAmount }
     *     
     */
    public MISMOAmount getIntegratedDisclosureSubsectionPaymentAmount() {
        return integratedDisclosureSubsectionPaymentAmount;
    }

    /**
     * Sets the value of the integratedDisclosureSubsectionPaymentAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link MISMOAmount }
     *     
     */
    public void setIntegratedDisclosureSubsectionPaymentAmount(MISMOAmount value) {
        this.integratedDisclosureSubsectionPaymentAmount = value;
    }

    /**
     * Gets the value of the integratedDisclosureSubsectionPaymentTimingType property.
     * 
     * @return
     *     possible object is
     *     {@link IntegratedDisclosureSubsectionPaymentTimingEnum }
     *     
     */
    public IntegratedDisclosureSubsectionPaymentTimingEnum getIntegratedDisclosureSubsectionPaymentTimingType() {
        return integratedDisclosureSubsectionPaymentTimingType;
    }

    /**
     * Sets the value of the integratedDisclosureSubsectionPaymentTimingType property.
     * 
     * @param value
     *     allowed object is
     *     {@link IntegratedDisclosureSubsectionPaymentTimingEnum }
     *     
     */
    public void setIntegratedDisclosureSubsectionPaymentTimingType(IntegratedDisclosureSubsectionPaymentTimingEnum value) {
        this.integratedDisclosureSubsectionPaymentTimingType = value;
    }

}
