//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.01 at 06:02:48 PM IST 
//


package org.mismo.residential._2009.schemas;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Attributes that apply in general to the calculation of interest rate for adjustable rate mortgages.
 * 
 * <p>Java class for INTEREST_RATE_ADJUSTMENT complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="INTEREST_RATE_ADJUSTMENT">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="INDEX_RULES" type="{http://www.mismo.org/residential/2009/schemas}INDEX_RULES" minOccurs="0"/>
 *         &lt;element name="INTEREST_RATE_LIFETIME_ADJUSTMENT_RULE" type="{http://www.mismo.org/residential/2009/schemas}INTEREST_RATE_LIFETIME_ADJUSTMENT_RULE" minOccurs="0"/>
 *         &lt;element name="INTEREST_RATE_PER_CHANGE_ADJUSTMENT_RULES" type="{http://www.mismo.org/residential/2009/schemas}INTEREST_RATE_PER_CHANGE_ADJUSTMENT_RULES" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "INTEREST_RATE_ADJUSTMENT", propOrder = {
    "indexrules",
    "interestratelifetimeadjustmentrule",
    "interestrateperchangeadjustmentrules"
})
public class INTERESTRATEADJUSTMENT {

    @XmlElement(name = "INDEX_RULES")
    protected INDEXRULES indexrules;
    @XmlElement(name = "INTEREST_RATE_LIFETIME_ADJUSTMENT_RULE")
    protected INTERESTRATELIFETIMEADJUSTMENTRULE interestratelifetimeadjustmentrule;
    @XmlElement(name = "INTEREST_RATE_PER_CHANGE_ADJUSTMENT_RULES")
    protected INTERESTRATEPERCHANGEADJUSTMENTRULES interestrateperchangeadjustmentrules;

    /**
     * Gets the value of the indexrules property.
     * 
     * @return
     *     possible object is
     *     {@link INDEXRULES }
     *     
     */
    public INDEXRULES getINDEXRULES() {
        return indexrules;
    }

    /**
     * Sets the value of the indexrules property.
     * 
     * @param value
     *     allowed object is
     *     {@link INDEXRULES }
     *     
     */
    public void setINDEXRULES(INDEXRULES value) {
        this.indexrules = value;
    }

    /**
     * Gets the value of the interestratelifetimeadjustmentrule property.
     * 
     * @return
     *     possible object is
     *     {@link INTERESTRATELIFETIMEADJUSTMENTRULE }
     *     
     */
    public INTERESTRATELIFETIMEADJUSTMENTRULE getINTERESTRATELIFETIMEADJUSTMENTRULE() {
        return interestratelifetimeadjustmentrule;
    }

    /**
     * Sets the value of the interestratelifetimeadjustmentrule property.
     * 
     * @param value
     *     allowed object is
     *     {@link INTERESTRATELIFETIMEADJUSTMENTRULE }
     *     
     */
    public void setINTERESTRATELIFETIMEADJUSTMENTRULE(INTERESTRATELIFETIMEADJUSTMENTRULE value) {
        this.interestratelifetimeadjustmentrule = value;
    }

    /**
     * Gets the value of the interestrateperchangeadjustmentrules property.
     * 
     * @return
     *     possible object is
     *     {@link INTERESTRATEPERCHANGEADJUSTMENTRULES }
     *     
     */
    public INTERESTRATEPERCHANGEADJUSTMENTRULES getINTERESTRATEPERCHANGEADJUSTMENTRULES() {
        return interestrateperchangeadjustmentrules;
    }

    /**
     * Sets the value of the interestrateperchangeadjustmentrules property.
     * 
     * @param value
     *     allowed object is
     *     {@link INTERESTRATEPERCHANGEADJUSTMENTRULES }
     *     
     */
    public void setINTERESTRATEPERCHANGEADJUSTMENTRULES(INTERESTRATEPERCHANGEADJUSTMENTRULES value) {
        this.interestrateperchangeadjustmentrules = value;
    }

}
