//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.01 at 06:02:48 PM IST 
//


package org.mismo.residential._2009.schemas;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * This is additional information that describes or identifies a legal entity.
 * 
 * <p>Java class for LEGAL_ENTITY complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LEGAL_ENTITY">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="LEGAL_ENTITY_DETAIL" type="{http://www.mismo.org/residential/2009/schemas}LEGAL_ENTITY_DETAIL" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LEGAL_ENTITY", propOrder = {
    "legalentitydetail"
})
public class LEGALENTITY {

    @XmlElement(name = "LEGAL_ENTITY_DETAIL")
    protected LEGALENTITYDETAIL legalentitydetail;

    /**
     * Gets the value of the legalentitydetail property.
     * 
     * @return
     *     possible object is
     *     {@link LEGALENTITYDETAIL }
     *     
     */
    public LEGALENTITYDETAIL getLEGALENTITYDETAIL() {
        return legalentitydetail;
    }

    /**
     * Sets the value of the legalentitydetail property.
     * 
     * @param value
     *     allowed object is
     *     {@link LEGALENTITYDETAIL }
     *     
     */
    public void setLEGALENTITYDETAIL(LEGALENTITYDETAIL value) {
        this.legalentitydetail = value;
    }

}
