//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.01 at 06:02:48 PM IST 
//


package org.mismo.residential._2009.schemas;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * A property description, recognized by law, that is sufficient to locate and identify the property without oral testimony.
 * 
 * <p>Java class for LEGAL_DESCRIPTION complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LEGAL_DESCRIPTION">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="UNPARSED_LEGAL_DESCRIPTIONS" type="{http://www.mismo.org/residential/2009/schemas}UNPARSED_LEGAL_DESCRIPTIONS" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LEGAL_DESCRIPTION", propOrder = {
    "unparsedlegaldescriptions"
})
public class LEGALDESCRIPTION {

    @XmlElement(name = "UNPARSED_LEGAL_DESCRIPTIONS")
    protected UNPARSEDLEGALDESCRIPTIONS unparsedlegaldescriptions;

    /**
     * Gets the value of the unparsedlegaldescriptions property.
     * 
     * @return
     *     possible object is
     *     {@link UNPARSEDLEGALDESCRIPTIONS }
     *     
     */
    public UNPARSEDLEGALDESCRIPTIONS getUNPARSEDLEGALDESCRIPTIONS() {
        return unparsedlegaldescriptions;
    }

    /**
     * Sets the value of the unparsedlegaldescriptions property.
     * 
     * @param value
     *     allowed object is
     *     {@link UNPARSEDLEGALDESCRIPTIONS }
     *     
     */
    public void setUNPARSEDLEGALDESCRIPTIONS(UNPARSEDLEGALDESCRIPTIONS value) {
        this.unparsedlegaldescriptions = value;
    }

}
