//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.01 at 06:02:48 PM IST 
//


package org.mismo.residential._2009.schemas;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Information regarding a specific type of license. A license is granted by an authority as permission to access, use or act on specified goods or services.
 * 
 * <p>Java class for LICENSE complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LICENSE">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="LICENSE_DETAIL" type="{http://www.mismo.org/residential/2009/schemas}LICENSE_DETAIL" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LICENSE", propOrder = {
    "licensedetail"
})
public class LICENSE {

    @XmlElement(name = "LICENSE_DETAIL")
    protected LICENSEDETAIL licensedetail;

    /**
     * Gets the value of the licensedetail property.
     * 
     * @return
     *     possible object is
     *     {@link LICENSEDETAIL }
     *     
     */
    public LICENSEDETAIL getLICENSEDETAIL() {
        return licensedetail;
    }

    /**
     * Sets the value of the licensedetail property.
     * 
     * @param value
     *     allowed object is
     *     {@link LICENSEDETAIL }
     *     
     */
    public void setLICENSEDETAIL(LICENSEDETAIL value) {
        this.licensedetail = value;
    }

}
