//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.01 at 06:02:48 PM IST 
//


package org.mismo.residential._2009.schemas;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LoanPurposeBase.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="LoanPurposeBase">
 *   &lt;restriction base="{http://www.mismo.org/residential/2009/schemas}MISMOEnum_Base">
 *     &lt;enumeration value="Purchase"/>
 *     &lt;enumeration value="Refinance"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "LoanPurposeBase")
@XmlEnum
public enum LoanPurposeBase {


    /**
     * A loan made in association with the original purchase of a piece of property.
     * 
     */
    @XmlEnumValue("Purchase")
    PURCHASE("Purchase"),

    /**
     * The repayment of a debt from proceeds of a new loan using the same property as security  or a mortgage secured by a property previously owned free and clear by the Borrower.
     * 
     */
    @XmlEnumValue("Refinance")
    REFINANCE("Refinance");
    private final String value;

    LoanPurposeBase(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static LoanPurposeBase fromValue(String v) {
        for (LoanPurposeBase c: LoanPurposeBase.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
