//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.01 at 06:02:48 PM IST 
//


package org.mismo.residential._2009.schemas;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Information about the price that is willing to pay for this DEAL to accomplish closing the DEAL. In a retail lender organization this SHOULD represent the prices as seen by the BORROWER. In a wholesate lending environment this SHOULD also represent the BORROWER price.  In both cases the retail commision or the broker fee will be represented as a price detail witin the quote.
 * 
 * <p>Java class for LOAN_PRICE_QUOTE complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LOAN_PRICE_QUOTE">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="LOAN_PRICE_QUOTE_DETAIL" type="{http://www.mismo.org/residential/2009/schemas}LOAN_PRICE_QUOTE_DETAIL" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LOAN_PRICE_QUOTE", propOrder = {
    "loanpricequotedetail"
})
public class LOANPRICEQUOTE {

    @XmlElement(name = "LOAN_PRICE_QUOTE_DETAIL")
    protected LOANPRICEQUOTEDETAIL loanpricequotedetail;

    /**
     * Gets the value of the loanpricequotedetail property.
     * 
     * @return
     *     possible object is
     *     {@link LOANPRICEQUOTEDETAIL }
     *     
     */
    public LOANPRICEQUOTEDETAIL getLOANPRICEQUOTEDETAIL() {
        return loanpricequotedetail;
    }

    /**
     * Sets the value of the loanpricequotedetail property.
     * 
     * @param value
     *     allowed object is
     *     {@link LOANPRICEQUOTEDETAIL }
     *     
     */
    public void setLOANPRICEQUOTEDETAIL(LOANPRICEQUOTEDETAIL value) {
        this.loanpricequotedetail = value;
    }

}
