//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.01 at 06:02:48 PM IST 
//


package org.mismo.residential._2009.schemas;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * The unit of time used to define the period over which the loan matures. Used in conjunction with Loan Maturity Period Count.
 * 
 * <p>Java class for LoanMaturityPeriodEnum complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LoanMaturityPeriodEnum">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.mismo.org/residential/2009/schemas>LoanMaturityPeriodBase">
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LoanMaturityPeriodEnum", propOrder = {
    "value"
})
public class LoanMaturityPeriodEnum {

    @XmlValue
    protected LoanMaturityPeriodBase value;

    /**
     * Term: Loan Maturity Period Type Definition: The unit of time used to define the period over which the loan matures. Used in conjunction with Loan Maturity Period Count.
     * 
     * @return
     *     possible object is
     *     {@link LoanMaturityPeriodBase }
     *     
     */
    public LoanMaturityPeriodBase getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link LoanMaturityPeriodBase }
     *     
     */
    public void setValue(LoanMaturityPeriodBase value) {
        this.value = value;
    }

}
