//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.01 at 06:02:48 PM IST 
//


package org.mismo.residential._2009.schemas;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * A collection of facts used as descriptors of the characteristics of a financial instrument for sale in the marketplace that an investor is willing to buy.
 * 
 * <p>Java class for LOAN_PRODUCT complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LOAN_PRODUCT">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="LOAN_PRICE_QUOTES" type="{http://www.mismo.org/residential/2009/schemas}LOAN_PRICE_QUOTES" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LOAN_PRODUCT", propOrder = {
    "loanpricequotes"
})
public class LOANPRODUCT {

    @XmlElement(name = "LOAN_PRICE_QUOTES")
    protected LOANPRICEQUOTES loanpricequotes;

    /**
     * Gets the value of the loanpricequotes property.
     * 
     * @return
     *     possible object is
     *     {@link LOANPRICEQUOTES }
     *     
     */
    public LOANPRICEQUOTES getLOANPRICEQUOTES() {
        return loanpricequotes;
    }

    /**
     * Sets the value of the loanpricequotes property.
     * 
     * @param value
     *     allowed object is
     *     {@link LOANPRICEQUOTES }
     *     
     */
    public void setLOANPRICEQUOTES(LOANPRICEQUOTES value) {
        this.loanpricequotes = value;
    }

}
