//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.01 at 06:02:48 PM IST 
//


package org.mismo.residential._2009.schemas;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MATURITY_RULE complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MATURITY_RULE">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="LoanMaturityPeriodCount" type="{http://www.mismo.org/residential/2009/schemas}MISMOCount" minOccurs="0"/>
 *         &lt;element name="LoanMaturityPeriodType" type="{http://www.mismo.org/residential/2009/schemas}LoanMaturityPeriodEnum" minOccurs="0"/>
 *         &lt;element name="LoanTermMaximumMonthsCount" type="{http://www.mismo.org/residential/2009/schemas}MISMOCount" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MATURITY_RULE", propOrder = {
    "loanMaturityPeriodCount",
    "loanMaturityPeriodType",
    "loanTermMaximumMonthsCount"
})
public class MATURITYRULE {

    @XmlElement(name = "LoanMaturityPeriodCount")
    protected MISMOCount loanMaturityPeriodCount;
    @XmlElement(name = "LoanMaturityPeriodType")
    protected LoanMaturityPeriodEnum loanMaturityPeriodType;
    @XmlElement(name = "LoanTermMaximumMonthsCount")
    protected MISMOCount loanTermMaximumMonthsCount;

    /**
     * Gets the value of the loanMaturityPeriodCount property.
     * 
     * @return
     *     possible object is
     *     {@link MISMOCount }
     *     
     */
    public MISMOCount getLoanMaturityPeriodCount() {
        return loanMaturityPeriodCount;
    }

    /**
     * Sets the value of the loanMaturityPeriodCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link MISMOCount }
     *     
     */
    public void setLoanMaturityPeriodCount(MISMOCount value) {
        this.loanMaturityPeriodCount = value;
    }

    /**
     * Gets the value of the loanMaturityPeriodType property.
     * 
     * @return
     *     possible object is
     *     {@link LoanMaturityPeriodEnum }
     *     
     */
    public LoanMaturityPeriodEnum getLoanMaturityPeriodType() {
        return loanMaturityPeriodType;
    }

    /**
     * Sets the value of the loanMaturityPeriodType property.
     * 
     * @param value
     *     allowed object is
     *     {@link LoanMaturityPeriodEnum }
     *     
     */
    public void setLoanMaturityPeriodType(LoanMaturityPeriodEnum value) {
        this.loanMaturityPeriodType = value;
    }

    /**
     * Gets the value of the loanTermMaximumMonthsCount property.
     * 
     * @return
     *     possible object is
     *     {@link MISMOCount }
     *     
     */
    public MISMOCount getLoanTermMaximumMonthsCount() {
        return loanTermMaximumMonthsCount;
    }

    /**
     * Sets the value of the loanTermMaximumMonthsCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link MISMOCount }
     *     
     */
    public void setLoanTermMaximumMonthsCount(MISMOCount value) {
        this.loanTermMaximumMonthsCount = value;
    }

}
