//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.01 at 06:02:48 PM IST 
//


package org.mismo.residential._2009.schemas;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 *   AUS  Enumerated Loan Features  MI Secondary Delivery Servicing AUS Servicing Transfer  MI Company Name Type 
 * 
 * <p>Java class for MICompanyNameEnum complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MICompanyNameEnum">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.mismo.org/residential/2009/schemas>MICompanyNameBase">
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MICompanyNameEnum", propOrder = {
    "value"
})
public class MICompanyNameEnum {

    @XmlValue
    protected MICompanyNameBase value;

    /**
     * Term: MI Company Name Type Definition: To convey the private MI company short/common name from whom the private mortgage insurance coverage was obtained.
     * 
     * @return
     *     possible object is
     *     {@link MICompanyNameBase }
     *     
     */
    public MICompanyNameBase getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link MICompanyNameBase }
     *     
     */
    public void setValue(MICompanyNameBase value) {
        this.value = value;
    }

}
