//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.01 at 06:02:48 PM IST 
//


package org.mismo.residential._2009.schemas;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * Identifies the highest level private or public sector entity under whose guidelines the mortgage is originated.
 * 
 * <p>Java class for MortgageEnum complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MortgageEnum">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.mismo.org/residential/2009/schemas>MortgageBase">
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MortgageEnum", propOrder = {
    "value"
})
public class MortgageEnum {

    @XmlValue
    protected MortgageBase value;

    /**
     * Term: Mortgage Type Definition: Identifies the highest level private or public sector entity under whose guidelines the mortgage is originated.
     * Term: Pool Mortgage Type Definition: Specifies mortgage type of the loans for the pool.
     * Term: Supplemental Mortgage Type Definition: Identifies another lower-level private or public sector agency under whose guidelines the mortgage is originated.
     * 
     * @return
     *     possible object is
     *     {@link MortgageBase }
     *     
     */
    public MortgageBase getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link MortgageBase }
     *     
     */
    public void setValue(MortgageBase value) {
        this.value = value;
    }

}
