//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.01 at 06:02:48 PM IST 
//


package org.mismo.residential._2009.schemas;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Information regarding loans with negative amortization.  Negative amortization is unpaid interest added to the mortgage principal. This applies to loans where the principal balance increases because the payments do not cover the interest.
 * 
 * <p>Java class for NEGATIVE_AMORTIZATION complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NEGATIVE_AMORTIZATION">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="NEGATIVE_AMORTIZATION_RULE" type="{http://www.mismo.org/residential/2009/schemas}NEGATIVE_AMORTIZATION_RULE" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NEGATIVE_AMORTIZATION", propOrder = {
    "negativeamortizationrule"
})
public class NEGATIVEAMORTIZATION {

    @XmlElement(name = "NEGATIVE_AMORTIZATION_RULE")
    protected NEGATIVEAMORTIZATIONRULE negativeamortizationrule;

    /**
     * Gets the value of the negativeamortizationrule property.
     * 
     * @return
     *     possible object is
     *     {@link NEGATIVEAMORTIZATIONRULE }
     *     
     */
    public NEGATIVEAMORTIZATIONRULE getNEGATIVEAMORTIZATIONRULE() {
        return negativeamortizationrule;
    }

    /**
     * Sets the value of the negativeamortizationrule property.
     * 
     * @param value
     *     allowed object is
     *     {@link NEGATIVEAMORTIZATIONRULE }
     *     
     */
    public void setNEGATIVEAMORTIZATIONRULE(NEGATIVEAMORTIZATIONRULE value) {
        this.negativeamortizationrule = value;
    }

}
