//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.01 at 06:02:48 PM IST 
//


package org.mismo.residential._2009.schemas;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for NEGATIVE_AMORTIZATION_RULE complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NEGATIVE_AMORTIZATION_RULE">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="NegativeAmortizationLimitMonthsCount" type="{http://www.mismo.org/residential/2009/schemas}MISMOCount" minOccurs="0"/>
 *         &lt;element name="NegativeAmortizationMaximumLoanBalanceAmount" type="{http://www.mismo.org/residential/2009/schemas}MISMOAmount" minOccurs="0"/>
 *         &lt;element name="NegativeAmortizationType" type="{http://www.mismo.org/residential/2009/schemas}NegativeAmortizationEnum" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NEGATIVE_AMORTIZATION_RULE", propOrder = {
    "negativeAmortizationLimitMonthsCount",
    "negativeAmortizationMaximumLoanBalanceAmount",
    "negativeAmortizationType"
})
public class NEGATIVEAMORTIZATIONRULE {

    @XmlElement(name = "NegativeAmortizationLimitMonthsCount")
    protected MISMOCount negativeAmortizationLimitMonthsCount;
    @XmlElement(name = "NegativeAmortizationMaximumLoanBalanceAmount")
    protected MISMOAmount negativeAmortizationMaximumLoanBalanceAmount;
    @XmlElement(name = "NegativeAmortizationType")
    protected NegativeAmortizationEnum negativeAmortizationType;

    /**
     * Gets the value of the negativeAmortizationLimitMonthsCount property.
     * 
     * @return
     *     possible object is
     *     {@link MISMOCount }
     *     
     */
    public MISMOCount getNegativeAmortizationLimitMonthsCount() {
        return negativeAmortizationLimitMonthsCount;
    }

    /**
     * Sets the value of the negativeAmortizationLimitMonthsCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link MISMOCount }
     *     
     */
    public void setNegativeAmortizationLimitMonthsCount(MISMOCount value) {
        this.negativeAmortizationLimitMonthsCount = value;
    }

    /**
     * Gets the value of the negativeAmortizationMaximumLoanBalanceAmount property.
     * 
     * @return
     *     possible object is
     *     {@link MISMOAmount }
     *     
     */
    public MISMOAmount getNegativeAmortizationMaximumLoanBalanceAmount() {
        return negativeAmortizationMaximumLoanBalanceAmount;
    }

    /**
     * Sets the value of the negativeAmortizationMaximumLoanBalanceAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link MISMOAmount }
     *     
     */
    public void setNegativeAmortizationMaximumLoanBalanceAmount(MISMOAmount value) {
        this.negativeAmortizationMaximumLoanBalanceAmount = value;
    }

    /**
     * Gets the value of the negativeAmortizationType property.
     * 
     * @return
     *     possible object is
     *     {@link NegativeAmortizationEnum }
     *     
     */
    public NegativeAmortizationEnum getNegativeAmortizationType() {
        return negativeAmortizationType;
    }

    /**
     * Sets the value of the negativeAmortizationType property.
     * 
     * @param value
     *     allowed object is
     *     {@link NegativeAmortizationEnum }
     *     
     */
    public void setNegativeAmortizationType(NegativeAmortizationEnum value) {
        this.negativeAmortizationType = value;
    }

}
