//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.01 at 06:02:48 PM IST 
//


package org.mismo.residential._2009.schemas;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * Add references to IETF use of compression encode combimation. Add clairification about order of compression and encoding.
 * 
 * <p>Java class for ObjectEncodingEnum complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ObjectEncodingEnum">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.mismo.org/residential/2009/schemas>ObjectEncodingBase">
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ObjectEncodingEnum", propOrder = {
    "value"
})
public class ObjectEncodingEnum {

    @XmlValue
    protected ObjectEncodingBase value;

    /**
     * Term: Object Encoding Type Definition: Specifies the type of encoding used by the resource.
     * 
     * @return
     *     possible object is
     *     {@link ObjectEncodingBase }
     *     
     */
    public ObjectEncodingBase getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link ObjectEncodingBase }
     *     
     */
    public void setValue(ObjectEncodingBase value) {
        this.value = value;
    }

}
