//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.01 at 06:02:48 PM IST 
//


package org.mismo.residential._2009.schemas;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OTHER_PAYMENT_RULE_EXTENSION complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OTHER_PAYMENT_RULE_EXTENSION">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.datamodelextension.org}TotalOptionalPaymentCount" minOccurs="0"/>
 *         &lt;element ref="{http://www.datamodelextension.org}TotalStepPaymentCount" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OTHER_PAYMENT_RULE_EXTENSION", propOrder = {
    "totalOptionalPaymentCount",
    "totalStepPaymentCount"
})
public class OTHERPAYMENTRULEEXTENSION {

    @XmlElement(name = "TotalOptionalPaymentCount", namespace = "http://www.datamodelextension.org")
    protected Integer totalOptionalPaymentCount;
    @XmlElement(name = "TotalStepPaymentCount", namespace = "http://www.datamodelextension.org")
    protected Integer totalStepPaymentCount;

    /**
     * Gets the value of the totalOptionalPaymentCount property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTotalOptionalPaymentCount() {
        return totalOptionalPaymentCount;
    }

    /**
     * Sets the value of the totalOptionalPaymentCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTotalOptionalPaymentCount(Integer value) {
        this.totalOptionalPaymentCount = value;
    }

    /**
     * Gets the value of the totalStepPaymentCount property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTotalStepPaymentCount() {
        return totalStepPaymentCount;
    }

    /**
     * Sets the value of the totalStepPaymentCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTotalStepPaymentCount(Integer value) {
        this.totalStepPaymentCount = value;
    }

}
