//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.01 at 06:02:48 PM IST 
//


package org.mismo.residential._2009.schemas;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.datamodelextension.IntegratedDisclosureSectionEnum;


/**
 * <p>Java class for OTHER_LIABILITY_DETAIL_EXTENSION complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OTHER_LIABILITY_DETAIL_EXTENSION">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.datamodelextension.org}IntegratedDisclosureSectionType" minOccurs="0"/>
 *         &lt;element ref="{http://www.datamodelextension.org}LiabilitySecuredBySubjectPropertyIndicator" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OTHER_LIABILITY_DETAIL_EXTENSION", propOrder = {
    "integratedDisclosureSectionType",
    "liabilitySecuredBySubjectPropertyIndicator"
})
public class OTHERLIABILITYDETAILEXTENSION {

    @XmlElement(name = "IntegratedDisclosureSectionType", namespace = "http://www.datamodelextension.org")
    protected IntegratedDisclosureSectionEnum integratedDisclosureSectionType;
    @XmlElement(name = "LiabilitySecuredBySubjectPropertyIndicator", namespace = "http://www.datamodelextension.org")
    protected Boolean liabilitySecuredBySubjectPropertyIndicator;

    /**
     * Gets the value of the integratedDisclosureSectionType property.
     * 
     * @return
     *     possible object is
     *     {@link IntegratedDisclosureSectionEnum }
     *     
     */
    public IntegratedDisclosureSectionEnum getIntegratedDisclosureSectionType() {
        return integratedDisclosureSectionType;
    }

    /**
     * Sets the value of the integratedDisclosureSectionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link IntegratedDisclosureSectionEnum }
     *     
     */
    public void setIntegratedDisclosureSectionType(IntegratedDisclosureSectionEnum value) {
        this.integratedDisclosureSectionType = value;
    }

    /**
     * Gets the value of the liabilitySecuredBySubjectPropertyIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isLiabilitySecuredBySubjectPropertyIndicator() {
        return liabilitySecuredBySubjectPropertyIndicator;
    }

    /**
     * Sets the value of the liabilitySecuredBySubjectPropertyIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setLiabilitySecuredBySubjectPropertyIndicator(Boolean value) {
        this.liabilitySecuredBySubjectPropertyIndicator = value;
    }

}
