//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.01 at 06:02:48 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.mismo.org/residential/2009/schemas", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED, 
xmlns = {
       @javax.xml.bind.annotation.XmlNs(prefix="mismo", namespaceURI="http://www.mismo.org/residential/2009/schemas"),
       @javax.xml.bind.annotation.XmlNs(prefix="xlink", namespaceURI="http://www.w3.org/1999/xlink"),
       @javax.xml.bind.annotation.XmlNs(prefix="gse", namespaceURI="http://www.datamodelextension.org")
   }
)
package org.mismo.residential._2009.schemas;
