//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.01 at 06:02:48 PM IST 
//


package org.mismo.residential._2009.schemas;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Describes the order and manner in which partial payments are applied for the loan.
 * 
 * <p>Java class for PARTIAL_PAYMENT complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PARTIAL_PAYMENT">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PartialPaymentApplicationMethodType" type="{http://www.mismo.org/residential/2009/schemas}PartialPaymentApplicationMethodEnum" minOccurs="0"/>
 *         &lt;element name="PartialPaymentApplicationMethodTypeOtherDescription" type="{http://www.mismo.org/residential/2009/schemas}MISMOString" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PARTIAL_PAYMENT", propOrder = {
    "partialPaymentApplicationMethodType",
    "partialPaymentApplicationMethodTypeOtherDescription"
})
public class PARTIALPAYMENT {

    @XmlElement(name = "PartialPaymentApplicationMethodType")
    protected PartialPaymentApplicationMethodEnum partialPaymentApplicationMethodType;
    @XmlElement(name = "PartialPaymentApplicationMethodTypeOtherDescription")
    protected MISMOString partialPaymentApplicationMethodTypeOtherDescription;

    /**
     * Gets the value of the partialPaymentApplicationMethodType property.
     * 
     * @return
     *     possible object is
     *     {@link PartialPaymentApplicationMethodEnum }
     *     
     */
    public PartialPaymentApplicationMethodEnum getPartialPaymentApplicationMethodType() {
        return partialPaymentApplicationMethodType;
    }

    /**
     * Sets the value of the partialPaymentApplicationMethodType property.
     * 
     * @param value
     *     allowed object is
     *     {@link PartialPaymentApplicationMethodEnum }
     *     
     */
    public void setPartialPaymentApplicationMethodType(PartialPaymentApplicationMethodEnum value) {
        this.partialPaymentApplicationMethodType = value;
    }

    /**
     * Gets the value of the partialPaymentApplicationMethodTypeOtherDescription property.
     * 
     * @return
     *     possible object is
     *     {@link MISMOString }
     *     
     */
    public MISMOString getPartialPaymentApplicationMethodTypeOtherDescription() {
        return partialPaymentApplicationMethodTypeOtherDescription;
    }

    /**
     * Sets the value of the partialPaymentApplicationMethodTypeOtherDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link MISMOString }
     *     
     */
    public void setPartialPaymentApplicationMethodTypeOtherDescription(MISMOString value) {
        this.partialPaymentApplicationMethodTypeOtherDescription = value;
    }

}
