//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.01 at 06:02:48 PM IST 
//


package org.mismo.residential._2009.schemas;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PartyRoleTypeOtherDescriptionBase.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="PartyRoleTypeOtherDescriptionBase">
 *   &lt;restriction base="{http://www.mismo.org/residential/2009/schemas}MISMOEnum_Base">
 *     &lt;enumeration value="NonTitleNonSpouseOwnershipInterest"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "PartyRoleTypeOtherDescriptionBase")
@XmlEnum
public enum PartyRoleTypeOtherDescriptionBase {

    @XmlEnumValue("NonTitleNonSpouseOwnershipInterest")
    NON_TITLE_NON_SPOUSE_OWNERSHIP_INTEREST("NonTitleNonSpouseOwnershipInterest");
    private final String value;

    PartyRoleTypeOtherDescriptionBase(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static PartyRoleTypeOtherDescriptionBase fromValue(String v) {
        for (PartyRoleTypeOtherDescriptionBase c: PartyRoleTypeOtherDescriptionBase.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
