//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.01 at 06:02:48 PM IST 
//


package org.mismo.residential._2009.schemas;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PartialPaymentApplicationMethodBase.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="PartialPaymentApplicationMethodBase">
 *   &lt;restriction base="{http://www.mismo.org/residential/2009/schemas}MISMOEnum_Base">
 *     &lt;enumeration value="ApplyPartialPayment"/>
 *     &lt;enumeration value="HoldUntilCompleteAmount"/>
 *     &lt;enumeration value="Other"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "PartialPaymentApplicationMethodBase")
@XmlEnum
public enum PartialPaymentApplicationMethodBase {

    @XmlEnumValue("ApplyPartialPayment")
    APPLY_PARTIAL_PAYMENT("ApplyPartialPayment"),
    @XmlEnumValue("HoldUntilCompleteAmount")
    HOLD_UNTIL_COMPLETE_AMOUNT("HoldUntilCompleteAmount"),
    @XmlEnumValue("Other")
    OTHER("Other");
    private final String value;

    PartialPaymentApplicationMethodBase(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static PartialPaymentApplicationMethodBase fromValue(String v) {
        for (PartialPaymentApplicationMethodBase c: PartialPaymentApplicationMethodBase.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
