//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.01 at 06:02:48 PM IST 
//


package org.mismo.residential._2009.schemas;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Specifies the dollar amount, party making the payment and timing for each payment making up the Prepaid Item Type and Prepaid Item Amount.
 * 
 * <p>Java class for PREPAID_ITEM_PAYMENT complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PREPAID_ITEM_PAYMENT">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PrepaidItemActualPaymentAmount" type="{http://www.mismo.org/residential/2009/schemas}MISMOAmount" minOccurs="0"/>
 *         &lt;element name="PrepaidItemPaymentPaidByType" type="{http://www.mismo.org/residential/2009/schemas}PrepaidItemPaymentPaidByEnum" minOccurs="0"/>
 *         &lt;element name="PrepaidItemPaymentTimingType" type="{http://www.mismo.org/residential/2009/schemas}PrepaidItemPaymentTimingEnum" minOccurs="0"/>
 *         &lt;element name="RegulationZPointsAndFeesIndicator" type="{http://www.mismo.org/residential/2009/schemas}MISMOIndicator" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PREPAID_ITEM_PAYMENT", propOrder = {
    "prepaidItemActualPaymentAmount",
    "prepaidItemPaymentPaidByType",
    "prepaidItemPaymentTimingType",
    "regulationZPointsAndFeesIndicator"
})
public class PREPAIDITEMPAYMENT {

    @XmlElement(name = "PrepaidItemActualPaymentAmount")
    protected MISMOAmount prepaidItemActualPaymentAmount;
    @XmlElement(name = "PrepaidItemPaymentPaidByType")
    protected PrepaidItemPaymentPaidByEnum prepaidItemPaymentPaidByType;
    @XmlElement(name = "PrepaidItemPaymentTimingType")
    protected PrepaidItemPaymentTimingEnum prepaidItemPaymentTimingType;
    @XmlElement(name = "RegulationZPointsAndFeesIndicator")
    protected MISMOIndicator regulationZPointsAndFeesIndicator;

    /**
     * Gets the value of the prepaidItemActualPaymentAmount property.
     * 
     * @return
     *     possible object is
     *     {@link MISMOAmount }
     *     
     */
    public MISMOAmount getPrepaidItemActualPaymentAmount() {
        return prepaidItemActualPaymentAmount;
    }

    /**
     * Sets the value of the prepaidItemActualPaymentAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link MISMOAmount }
     *     
     */
    public void setPrepaidItemActualPaymentAmount(MISMOAmount value) {
        this.prepaidItemActualPaymentAmount = value;
    }

    /**
     * Gets the value of the prepaidItemPaymentPaidByType property.
     * 
     * @return
     *     possible object is
     *     {@link PrepaidItemPaymentPaidByEnum }
     *     
     */
    public PrepaidItemPaymentPaidByEnum getPrepaidItemPaymentPaidByType() {
        return prepaidItemPaymentPaidByType;
    }

    /**
     * Sets the value of the prepaidItemPaymentPaidByType property.
     * 
     * @param value
     *     allowed object is
     *     {@link PrepaidItemPaymentPaidByEnum }
     *     
     */
    public void setPrepaidItemPaymentPaidByType(PrepaidItemPaymentPaidByEnum value) {
        this.prepaidItemPaymentPaidByType = value;
    }

    /**
     * Gets the value of the prepaidItemPaymentTimingType property.
     * 
     * @return
     *     possible object is
     *     {@link PrepaidItemPaymentTimingEnum }
     *     
     */
    public PrepaidItemPaymentTimingEnum getPrepaidItemPaymentTimingType() {
        return prepaidItemPaymentTimingType;
    }

    /**
     * Sets the value of the prepaidItemPaymentTimingType property.
     * 
     * @param value
     *     allowed object is
     *     {@link PrepaidItemPaymentTimingEnum }
     *     
     */
    public void setPrepaidItemPaymentTimingType(PrepaidItemPaymentTimingEnum value) {
        this.prepaidItemPaymentTimingType = value;
    }

    /**
     * Gets the value of the regulationZPointsAndFeesIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link MISMOIndicator }
     *     
     */
    public MISMOIndicator getRegulationZPointsAndFeesIndicator() {
        return regulationZPointsAndFeesIndicator;
    }

    /**
     * Sets the value of the regulationZPointsAndFeesIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link MISMOIndicator }
     *     
     */
    public void setRegulationZPointsAndFeesIndicator(MISMOIndicator value) {
        this.regulationZPointsAndFeesIndicator = value;
    }

}
