//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.01 at 06:02:48 PM IST 
//


package org.mismo.residential._2009.schemas;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Data that describes the rules that govern one or more principal and interest payment adjustments.
 * 
 * <p>Java class for PRINCIPAL_AND_INTEREST_PAYMENT_PER_CHANGE_ADJUSTMENT_RULE complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PRINCIPAL_AND_INTEREST_PAYMENT_PER_CHANGE_ADJUSTMENT_RULE">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AdjustmentRuleType" type="{http://www.mismo.org/residential/2009/schemas}AdjustmentRuleEnum" minOccurs="0"/>
 *         &lt;element name="PerChangeMaximumPrincipalAndInterestPaymentAmount" type="{http://www.mismo.org/residential/2009/schemas}MISMOAmount" minOccurs="0"/>
 *         &lt;element name="PerChangeMinimumPrincipalAndInterestPaymentAmount" type="{http://www.mismo.org/residential/2009/schemas}MISMOAmount" minOccurs="0"/>
 *         &lt;element name="PerChangePrincipalAndInterestPaymentAdjustmentFrequencyMonthsCount" type="{http://www.mismo.org/residential/2009/schemas}MISMOCount" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PRINCIPAL_AND_INTEREST_PAYMENT_PER_CHANGE_ADJUSTMENT_RULE", propOrder = {
    "adjustmentRuleType",
    "perChangeMaximumPrincipalAndInterestPaymentAmount",
    "perChangeMinimumPrincipalAndInterestPaymentAmount",
    "perChangePrincipalAndInterestPaymentAdjustmentFrequencyMonthsCount"
})
public class PRINCIPALANDINTERESTPAYMENTPERCHANGEADJUSTMENTRULE {

    @XmlElement(name = "AdjustmentRuleType")
    protected AdjustmentRuleEnum adjustmentRuleType;
    @XmlElement(name = "PerChangeMaximumPrincipalAndInterestPaymentAmount")
    protected MISMOAmount perChangeMaximumPrincipalAndInterestPaymentAmount;
    @XmlElement(name = "PerChangeMinimumPrincipalAndInterestPaymentAmount")
    protected MISMOAmount perChangeMinimumPrincipalAndInterestPaymentAmount;
    @XmlElement(name = "PerChangePrincipalAndInterestPaymentAdjustmentFrequencyMonthsCount")
    protected MISMOCount perChangePrincipalAndInterestPaymentAdjustmentFrequencyMonthsCount;

    /**
     * Gets the value of the adjustmentRuleType property.
     * 
     * @return
     *     possible object is
     *     {@link AdjustmentRuleEnum }
     *     
     */
    public AdjustmentRuleEnum getAdjustmentRuleType() {
        return adjustmentRuleType;
    }

    /**
     * Sets the value of the adjustmentRuleType property.
     * 
     * @param value
     *     allowed object is
     *     {@link AdjustmentRuleEnum }
     *     
     */
    public void setAdjustmentRuleType(AdjustmentRuleEnum value) {
        this.adjustmentRuleType = value;
    }

    /**
     * Gets the value of the perChangeMaximumPrincipalAndInterestPaymentAmount property.
     * 
     * @return
     *     possible object is
     *     {@link MISMOAmount }
     *     
     */
    public MISMOAmount getPerChangeMaximumPrincipalAndInterestPaymentAmount() {
        return perChangeMaximumPrincipalAndInterestPaymentAmount;
    }

    /**
     * Sets the value of the perChangeMaximumPrincipalAndInterestPaymentAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link MISMOAmount }
     *     
     */
    public void setPerChangeMaximumPrincipalAndInterestPaymentAmount(MISMOAmount value) {
        this.perChangeMaximumPrincipalAndInterestPaymentAmount = value;
    }

    /**
     * Gets the value of the perChangeMinimumPrincipalAndInterestPaymentAmount property.
     * 
     * @return
     *     possible object is
     *     {@link MISMOAmount }
     *     
     */
    public MISMOAmount getPerChangeMinimumPrincipalAndInterestPaymentAmount() {
        return perChangeMinimumPrincipalAndInterestPaymentAmount;
    }

    /**
     * Sets the value of the perChangeMinimumPrincipalAndInterestPaymentAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link MISMOAmount }
     *     
     */
    public void setPerChangeMinimumPrincipalAndInterestPaymentAmount(MISMOAmount value) {
        this.perChangeMinimumPrincipalAndInterestPaymentAmount = value;
    }

    /**
     * Gets the value of the perChangePrincipalAndInterestPaymentAdjustmentFrequencyMonthsCount property.
     * 
     * @return
     *     possible object is
     *     {@link MISMOCount }
     *     
     */
    public MISMOCount getPerChangePrincipalAndInterestPaymentAdjustmentFrequencyMonthsCount() {
        return perChangePrincipalAndInterestPaymentAdjustmentFrequencyMonthsCount;
    }

    /**
     * Sets the value of the perChangePrincipalAndInterestPaymentAdjustmentFrequencyMonthsCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link MISMOCount }
     *     
     */
    public void setPerChangePrincipalAndInterestPaymentAdjustmentFrequencyMonthsCount(MISMOCount value) {
        this.perChangePrincipalAndInterestPaymentAdjustmentFrequencyMonthsCount = value;
    }

}
