//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.01 at 06:02:48 PM IST 
//


package org.mismo.residential._2009.schemas;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Data that describes the rules that that apply to principal and interest payment adjustments in effect for the entire life of the loan or for a single unique occurrence such as a first rate adjustment. In general the element are usually known at the time of closing.
 * 
 * <p>Java class for PRINCIPAL_AND_INTEREST_PAYMENT_LIFETIME_ADJUSTMENT_RULE complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PRINCIPAL_AND_INTEREST_PAYMENT_LIFETIME_ADJUSTMENT_RULE">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="FirstPrincipalAndInterestPaymentChangeMonthsCount" type="{http://www.mismo.org/residential/2009/schemas}MISMOCount" minOccurs="0"/>
 *         &lt;element name="PrincipalAndInterestPaymentMaximumAmount" type="{http://www.mismo.org/residential/2009/schemas}MISMOAmount" minOccurs="0"/>
 *         &lt;element name="PrincipalAndInterestPaymentMaximumAmountEarliestEffectiveMonthsCount" type="{http://www.mismo.org/residential/2009/schemas}MISMOCount" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PRINCIPAL_AND_INTEREST_PAYMENT_LIFETIME_ADJUSTMENT_RULE", propOrder = {
    "firstPrincipalAndInterestPaymentChangeMonthsCount",
    "principalAndInterestPaymentMaximumAmount",
    "principalAndInterestPaymentMaximumAmountEarliestEffectiveMonthsCount"
})
public class PRINCIPALANDINTERESTPAYMENTLIFETIMEADJUSTMENTRULE {

    @XmlElement(name = "FirstPrincipalAndInterestPaymentChangeMonthsCount")
    protected MISMOCount firstPrincipalAndInterestPaymentChangeMonthsCount;
    @XmlElement(name = "PrincipalAndInterestPaymentMaximumAmount")
    protected MISMOAmount principalAndInterestPaymentMaximumAmount;
    @XmlElement(name = "PrincipalAndInterestPaymentMaximumAmountEarliestEffectiveMonthsCount")
    protected MISMOCount principalAndInterestPaymentMaximumAmountEarliestEffectiveMonthsCount;

    /**
     * Gets the value of the firstPrincipalAndInterestPaymentChangeMonthsCount property.
     * 
     * @return
     *     possible object is
     *     {@link MISMOCount }
     *     
     */
    public MISMOCount getFirstPrincipalAndInterestPaymentChangeMonthsCount() {
        return firstPrincipalAndInterestPaymentChangeMonthsCount;
    }

    /**
     * Sets the value of the firstPrincipalAndInterestPaymentChangeMonthsCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link MISMOCount }
     *     
     */
    public void setFirstPrincipalAndInterestPaymentChangeMonthsCount(MISMOCount value) {
        this.firstPrincipalAndInterestPaymentChangeMonthsCount = value;
    }

    /**
     * Gets the value of the principalAndInterestPaymentMaximumAmount property.
     * 
     * @return
     *     possible object is
     *     {@link MISMOAmount }
     *     
     */
    public MISMOAmount getPrincipalAndInterestPaymentMaximumAmount() {
        return principalAndInterestPaymentMaximumAmount;
    }

    /**
     * Sets the value of the principalAndInterestPaymentMaximumAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link MISMOAmount }
     *     
     */
    public void setPrincipalAndInterestPaymentMaximumAmount(MISMOAmount value) {
        this.principalAndInterestPaymentMaximumAmount = value;
    }

    /**
     * Gets the value of the principalAndInterestPaymentMaximumAmountEarliestEffectiveMonthsCount property.
     * 
     * @return
     *     possible object is
     *     {@link MISMOCount }
     *     
     */
    public MISMOCount getPrincipalAndInterestPaymentMaximumAmountEarliestEffectiveMonthsCount() {
        return principalAndInterestPaymentMaximumAmountEarliestEffectiveMonthsCount;
    }

    /**
     * Sets the value of the principalAndInterestPaymentMaximumAmountEarliestEffectiveMonthsCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link MISMOCount }
     *     
     */
    public void setPrincipalAndInterestPaymentMaximumAmountEarliestEffectiveMonthsCount(MISMOCount value) {
        this.principalAndInterestPaymentMaximumAmountEarliestEffectiveMonthsCount = value;
    }

}
