//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.01 at 06:02:48 PM IST 
//


package org.mismo.residential._2009.schemas;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Information specific to a real estate in terms of land structure, location and market. 
 * 
 * <p>Java class for PROPERTY complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PROPERTY">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ADDRESS" type="{http://www.mismo.org/residential/2009/schemas}ADDRESS"/>
 *         &lt;element name="LEGAL_DESCRIPTIONS" type="{http://www.mismo.org/residential/2009/schemas}LEGAL_DESCRIPTIONS" minOccurs="0"/>
 *         &lt;element name="PROPERTY_DETAIL" type="{http://www.mismo.org/residential/2009/schemas}PROPERTY_DETAIL" minOccurs="0"/>
 *         &lt;element name="PROPERTY_VALUATIONS" type="{http://www.mismo.org/residential/2009/schemas}PROPERTY_VALUATIONS" minOccurs="0"/>
 *         &lt;element name="SALES_CONTRACTS" type="{http://www.mismo.org/residential/2009/schemas}SALES_CONTRACTS" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PROPERTY", propOrder = {
    "address",
    "legaldescriptions",
    "propertydetail",
    "propertyvaluations",
    "salescontracts"
})
public class PROPERTY {

    @XmlElement(name = "ADDRESS", required = true)
    protected ADDRESS address;
    @XmlElement(name = "LEGAL_DESCRIPTIONS")
    protected LEGALDESCRIPTIONS legaldescriptions;
    @XmlElement(name = "PROPERTY_DETAIL")
    protected PROPERTYDETAIL propertydetail;
    @XmlElement(name = "PROPERTY_VALUATIONS")
    protected PROPERTYVALUATIONS propertyvaluations;
    @XmlElement(name = "SALES_CONTRACTS")
    protected SALESCONTRACTS salescontracts;

    /**
     * Gets the value of the address property.
     * 
     * @return
     *     possible object is
     *     {@link ADDRESS }
     *     
     */
    public ADDRESS getADDRESS() {
        return address;
    }

    /**
     * Sets the value of the address property.
     * 
     * @param value
     *     allowed object is
     *     {@link ADDRESS }
     *     
     */
    public void setADDRESS(ADDRESS value) {
        this.address = value;
    }

    /**
     * Gets the value of the legaldescriptions property.
     * 
     * @return
     *     possible object is
     *     {@link LEGALDESCRIPTIONS }
     *     
     */
    public LEGALDESCRIPTIONS getLEGALDESCRIPTIONS() {
        return legaldescriptions;
    }

    /**
     * Sets the value of the legaldescriptions property.
     * 
     * @param value
     *     allowed object is
     *     {@link LEGALDESCRIPTIONS }
     *     
     */
    public void setLEGALDESCRIPTIONS(LEGALDESCRIPTIONS value) {
        this.legaldescriptions = value;
    }

    /**
     * Gets the value of the propertydetail property.
     * 
     * @return
     *     possible object is
     *     {@link PROPERTYDETAIL }
     *     
     */
    public PROPERTYDETAIL getPROPERTYDETAIL() {
        return propertydetail;
    }

    /**
     * Sets the value of the propertydetail property.
     * 
     * @param value
     *     allowed object is
     *     {@link PROPERTYDETAIL }
     *     
     */
    public void setPROPERTYDETAIL(PROPERTYDETAIL value) {
        this.propertydetail = value;
    }

    /**
     * Gets the value of the propertyvaluations property.
     * 
     * @return
     *     possible object is
     *     {@link PROPERTYVALUATIONS }
     *     
     */
    public PROPERTYVALUATIONS getPROPERTYVALUATIONS() {
        return propertyvaluations;
    }

    /**
     * Sets the value of the propertyvaluations property.
     * 
     * @param value
     *     allowed object is
     *     {@link PROPERTYVALUATIONS }
     *     
     */
    public void setPROPERTYVALUATIONS(PROPERTYVALUATIONS value) {
        this.propertyvaluations = value;
    }

    /**
     * Gets the value of the salescontracts property.
     * 
     * @return
     *     possible object is
     *     {@link SALESCONTRACTS }
     *     
     */
    public SALESCONTRACTS getSALESCONTRACTS() {
        return salescontracts;
    }

    /**
     * Sets the value of the salescontracts property.
     * 
     * @param value
     *     allowed object is
     *     {@link SALESCONTRACTS }
     *     
     */
    public void setSALESCONTRACTS(SALESCONTRACTS value) {
        this.salescontracts = value;
    }

}
