//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.01 at 06:02:48 PM IST 
//


package org.mismo.residential._2009.schemas;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Information regarding the type and result of a valuation ordered and/or received on the property, both original and current. A given result may be from either an automated or traditional valuation method. 
 * 
 * <p>Java class for PROPERTY_VALUATION complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PROPERTY_VALUATION">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PROPERTY_VALUATION_DETAIL" type="{http://www.mismo.org/residential/2009/schemas}PROPERTY_VALUATION_DETAIL" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PROPERTY_VALUATION", propOrder = {
    "propertyvaluationdetail"
})
public class PROPERTYVALUATION {

    @XmlElement(name = "PROPERTY_VALUATION_DETAIL")
    protected PROPERTYVALUATIONDETAIL propertyvaluationdetail;

    /**
     * Gets the value of the propertyvaluationdetail property.
     * 
     * @return
     *     possible object is
     *     {@link PROPERTYVALUATIONDETAIL }
     *     
     */
    public PROPERTYVALUATIONDETAIL getPROPERTYVALUATIONDETAIL() {
        return propertyvaluationdetail;
    }

    /**
     * Sets the value of the propertyvaluationdetail property.
     * 
     * @param value
     *     allowed object is
     *     {@link PROPERTYVALUATIONDETAIL }
     *     
     */
    public void setPROPERTYVALUATIONDETAIL(PROPERTYVALUATIONDETAIL value) {
        this.propertyvaluationdetail = value;
    }

}
