//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.01 at 06:02:48 PM IST 
//


package org.mismo.residential._2009.schemas;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PROPERTY_VALUATION_DETAIL complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PROPERTY_VALUATION_DETAIL">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AppraisalIdentifier" type="{http://www.mismo.org/residential/2009/schemas}MISMOIdentifier" minOccurs="0"/>
 *         &lt;element name="PropertyValuationAmount" type="{http://www.mismo.org/residential/2009/schemas}MISMOAmount" minOccurs="0"/>
 *         &lt;element name="PropertyValuationMethodType" type="{http://www.mismo.org/residential/2009/schemas}PropertyValuationMethodEnum" minOccurs="0"/>
 *         &lt;element name="PropertyValuationMethodTypeOtherDescription" type="{http://www.mismo.org/residential/2009/schemas}MISMOString" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PROPERTY_VALUATION_DETAIL", propOrder = {
    "appraisalIdentifier",
    "propertyValuationAmount",
    "propertyValuationMethodType",
    "propertyValuationMethodTypeOtherDescription"
})
public class PROPERTYVALUATIONDETAIL {

    @XmlElement(name = "AppraisalIdentifier")
    protected MISMOIdentifier appraisalIdentifier;
    @XmlElement(name = "PropertyValuationAmount")
    protected MISMOAmount propertyValuationAmount;
    @XmlElement(name = "PropertyValuationMethodType")
    protected PropertyValuationMethodEnum propertyValuationMethodType;
    @XmlElement(name = "PropertyValuationMethodTypeOtherDescription")
    protected MISMOString propertyValuationMethodTypeOtherDescription;

    /**
     * Gets the value of the appraisalIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link MISMOIdentifier }
     *     
     */
    public MISMOIdentifier getAppraisalIdentifier() {
        return appraisalIdentifier;
    }

    /**
     * Sets the value of the appraisalIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link MISMOIdentifier }
     *     
     */
    public void setAppraisalIdentifier(MISMOIdentifier value) {
        this.appraisalIdentifier = value;
    }

    /**
     * Gets the value of the propertyValuationAmount property.
     * 
     * @return
     *     possible object is
     *     {@link MISMOAmount }
     *     
     */
    public MISMOAmount getPropertyValuationAmount() {
        return propertyValuationAmount;
    }

    /**
     * Sets the value of the propertyValuationAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link MISMOAmount }
     *     
     */
    public void setPropertyValuationAmount(MISMOAmount value) {
        this.propertyValuationAmount = value;
    }

    /**
     * Gets the value of the propertyValuationMethodType property.
     * 
     * @return
     *     possible object is
     *     {@link PropertyValuationMethodEnum }
     *     
     */
    public PropertyValuationMethodEnum getPropertyValuationMethodType() {
        return propertyValuationMethodType;
    }

    /**
     * Sets the value of the propertyValuationMethodType property.
     * 
     * @param value
     *     allowed object is
     *     {@link PropertyValuationMethodEnum }
     *     
     */
    public void setPropertyValuationMethodType(PropertyValuationMethodEnum value) {
        this.propertyValuationMethodType = value;
    }

    /**
     * Gets the value of the propertyValuationMethodTypeOtherDescription property.
     * 
     * @return
     *     possible object is
     *     {@link MISMOString }
     *     
     */
    public MISMOString getPropertyValuationMethodTypeOtherDescription() {
        return propertyValuationMethodTypeOtherDescription;
    }

    /**
     * Sets the value of the propertyValuationMethodTypeOtherDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link MISMOString }
     *     
     */
    public void setPropertyValuationMethodTypeOtherDescription(MISMOString value) {
        this.propertyValuationMethodTypeOtherDescription = value;
    }

}
