//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.01 at 06:02:48 PM IST 
//


package org.mismo.residential._2009.schemas;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Describes characteristics of the loan, including the behavior defined in the financial instrument.
 * 
 * <p>Java class for TERMS_OF_LOAN complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TERMS_OF_LOAN">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AssumedLoanAmount" type="{http://www.mismo.org/residential/2009/schemas}MISMOAmount" minOccurs="0"/>
 *         &lt;element name="DisclosedFullyIndexedRatePercent" type="{http://www.mismo.org/residential/2009/schemas}MISMOPercent" minOccurs="0"/>
 *         &lt;element name="LienPriorityType" type="{http://www.mismo.org/residential/2009/schemas}LienPriorityEnum" minOccurs="0"/>
 *         &lt;element name="LoanPurposeType" type="{http://www.mismo.org/residential/2009/schemas}LoanPurposeEnum" minOccurs="0"/>
 *         &lt;element name="MortgageType" type="{http://www.mismo.org/residential/2009/schemas}MortgageEnum" minOccurs="0"/>
 *         &lt;element name="MortgageTypeOtherDescription" type="{http://www.mismo.org/residential/2009/schemas}MISMOString" minOccurs="0"/>
 *         &lt;element name="NoteAmount" type="{http://www.mismo.org/residential/2009/schemas}MISMOAmount" minOccurs="0"/>
 *         &lt;element name="NoteRatePercent" type="{http://www.mismo.org/residential/2009/schemas}MISMOPercent" minOccurs="0"/>
 *         &lt;element name="WeightedAverageInterestRatePercent" type="{http://www.mismo.org/residential/2009/schemas}MISMOPercent" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TERMS_OF_LOAN", propOrder = {
    "assumedLoanAmount",
    "disclosedFullyIndexedRatePercent",
    "lienPriorityType",
    "loanPurposeType",
    "mortgageType",
    "mortgageTypeOtherDescription",
    "noteAmount",
    "noteRatePercent",
    "weightedAverageInterestRatePercent"
})
public class TERMSOFLOAN {

    @XmlElement(name = "AssumedLoanAmount")
    protected MISMOAmount assumedLoanAmount;
    @XmlElement(name = "DisclosedFullyIndexedRatePercent")
    protected MISMOPercent disclosedFullyIndexedRatePercent;
    @XmlElement(name = "LienPriorityType")
    protected LienPriorityEnum lienPriorityType;
    @XmlElement(name = "LoanPurposeType")
    protected LoanPurposeEnum loanPurposeType;
    @XmlElement(name = "MortgageType")
    protected MortgageEnum mortgageType;
    @XmlElement(name = "MortgageTypeOtherDescription")
    protected MISMOString mortgageTypeOtherDescription;
    @XmlElement(name = "NoteAmount")
    protected MISMOAmount noteAmount;
    @XmlElement(name = "NoteRatePercent")
    protected MISMOPercent noteRatePercent;
    @XmlElement(name = "WeightedAverageInterestRatePercent")
    protected MISMOPercent weightedAverageInterestRatePercent;

    /**
     * Gets the value of the assumedLoanAmount property.
     * 
     * @return
     *     possible object is
     *     {@link MISMOAmount }
     *     
     */
    public MISMOAmount getAssumedLoanAmount() {
        return assumedLoanAmount;
    }

    /**
     * Sets the value of the assumedLoanAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link MISMOAmount }
     *     
     */
    public void setAssumedLoanAmount(MISMOAmount value) {
        this.assumedLoanAmount = value;
    }

    /**
     * Gets the value of the disclosedFullyIndexedRatePercent property.
     * 
     * @return
     *     possible object is
     *     {@link MISMOPercent }
     *     
     */
    public MISMOPercent getDisclosedFullyIndexedRatePercent() {
        return disclosedFullyIndexedRatePercent;
    }

    /**
     * Sets the value of the disclosedFullyIndexedRatePercent property.
     * 
     * @param value
     *     allowed object is
     *     {@link MISMOPercent }
     *     
     */
    public void setDisclosedFullyIndexedRatePercent(MISMOPercent value) {
        this.disclosedFullyIndexedRatePercent = value;
    }

    /**
     * Gets the value of the lienPriorityType property.
     * 
     * @return
     *     possible object is
     *     {@link LienPriorityEnum }
     *     
     */
    public LienPriorityEnum getLienPriorityType() {
        return lienPriorityType;
    }

    /**
     * Sets the value of the lienPriorityType property.
     * 
     * @param value
     *     allowed object is
     *     {@link LienPriorityEnum }
     *     
     */
    public void setLienPriorityType(LienPriorityEnum value) {
        this.lienPriorityType = value;
    }

    /**
     * Gets the value of the loanPurposeType property.
     * 
     * @return
     *     possible object is
     *     {@link LoanPurposeEnum }
     *     
     */
    public LoanPurposeEnum getLoanPurposeType() {
        return loanPurposeType;
    }

    /**
     * Sets the value of the loanPurposeType property.
     * 
     * @param value
     *     allowed object is
     *     {@link LoanPurposeEnum }
     *     
     */
    public void setLoanPurposeType(LoanPurposeEnum value) {
        this.loanPurposeType = value;
    }

    /**
     * Gets the value of the mortgageType property.
     * 
     * @return
     *     possible object is
     *     {@link MortgageEnum }
     *     
     */
    public MortgageEnum getMortgageType() {
        return mortgageType;
    }

    /**
     * Sets the value of the mortgageType property.
     * 
     * @param value
     *     allowed object is
     *     {@link MortgageEnum }
     *     
     */
    public void setMortgageType(MortgageEnum value) {
        this.mortgageType = value;
    }

    /**
     * Gets the value of the mortgageTypeOtherDescription property.
     * 
     * @return
     *     possible object is
     *     {@link MISMOString }
     *     
     */
    public MISMOString getMortgageTypeOtherDescription() {
        return mortgageTypeOtherDescription;
    }

    /**
     * Sets the value of the mortgageTypeOtherDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link MISMOString }
     *     
     */
    public void setMortgageTypeOtherDescription(MISMOString value) {
        this.mortgageTypeOtherDescription = value;
    }

    /**
     * Gets the value of the noteAmount property.
     * 
     * @return
     *     possible object is
     *     {@link MISMOAmount }
     *     
     */
    public MISMOAmount getNoteAmount() {
        return noteAmount;
    }

    /**
     * Sets the value of the noteAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link MISMOAmount }
     *     
     */
    public void setNoteAmount(MISMOAmount value) {
        this.noteAmount = value;
    }

    /**
     * Gets the value of the noteRatePercent property.
     * 
     * @return
     *     possible object is
     *     {@link MISMOPercent }
     *     
     */
    public MISMOPercent getNoteRatePercent() {
        return noteRatePercent;
    }

    /**
     * Sets the value of the noteRatePercent property.
     * 
     * @param value
     *     allowed object is
     *     {@link MISMOPercent }
     *     
     */
    public void setNoteRatePercent(MISMOPercent value) {
        this.noteRatePercent = value;
    }

    /**
     * Gets the value of the weightedAverageInterestRatePercent property.
     * 
     * @return
     *     possible object is
     *     {@link MISMOPercent }
     *     
     */
    public MISMOPercent getWeightedAverageInterestRatePercent() {
        return weightedAverageInterestRatePercent;
    }

    /**
     * Sets the value of the weightedAverageInterestRatePercent property.
     * 
     * @param value
     *     allowed object is
     *     {@link MISMOPercent }
     *     
     */
    public void setWeightedAverageInterestRatePercent(MISMOPercent value) {
        this.weightedAverageInterestRatePercent = value;
    }

}
