//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.01 at 06:02:48 PM IST 
//


package org.datamodelextension;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.mismo.residential._2009.schemas.LEGALENTITY;


/**
 * <p>Java class for CLOSING_ADJUSTMENT_ITEM_PAID_TO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CLOSING_ADJUSTMENT_ITEM_PAID_TO">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.mismo.org/residential/2009/schemas}LEGAL_ENTITY" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CLOSING_ADJUSTMENT_ITEM_PAID_TO", propOrder = {
    "legalentity"
})
public class CLOSINGADJUSTMENTITEMPAIDTO {

    @XmlElement(name = "LEGAL_ENTITY", namespace = "http://www.mismo.org/residential/2009/schemas")
    protected LEGALENTITY legalentity;

    /**
     * Gets the value of the legalentity property.
     * 
     * @return
     *     possible object is
     *     {@link LEGALENTITY }
     *     
     */
    public LEGALENTITY getLEGALENTITY() {
        return legalentity;
    }

    /**
     * Sets the value of the legalentity property.
     * 
     * @param value
     *     allowed object is
     *     {@link LEGALENTITY }
     *     
     */
    public void setLEGALENTITY(LEGALENTITY value) {
        this.legalentity = value;
    }

}
