//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.01 at 06:02:48 PM IST 
//


package org.datamodelextension;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.mismo.residential._2009.schemas.LATECHARGERULE;


/**
 * <p>Java class for LATE_CHARGE_RULES complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LATE_CHARGE_RULES">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.mismo.org/residential/2009/schemas}LATE_CHARGE_RULE" maxOccurs="2"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LATE_CHARGE_RULES", propOrder = {
    "latechargerule"
})
public class LATECHARGERULES {

    @XmlElement(name = "LATE_CHARGE_RULE", namespace = "http://www.mismo.org/residential/2009/schemas", required = true)
    protected List<LATECHARGERULE> latechargerule;

    /**
     * Gets the value of the latechargerule property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the latechargerule property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLATECHARGERULE().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LATECHARGERULE }
     * 
     * 
     */
    public List<LATECHARGERULE> getLATECHARGERULE() {
        if (latechargerule == null) {
            latechargerule = new ArrayList<LATECHARGERULE>();
        }
        return this.latechargerule;
    }

}
