//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.01 at 06:02:48 PM IST 
//


package org.datamodelextension;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.datamodelextension package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _CLOSINGADJUSTMENTITEMPAIDTO_QNAME = new QName("http://www.datamodelextension.org", "CLOSING_ADJUSTMENT_ITEM_PAID_TO");
    private final static QName _BuydownReflectedInNoteIndicator_QNAME = new QName("http://www.datamodelextension.org", "BuydownReflectedInNoteIndicator");
    private final static QName _IntegratedDisclosureSectionType_QNAME = new QName("http://www.datamodelextension.org", "IntegratedDisclosureSectionType");
    private final static QName _LATECHARGERULES_QNAME = new QName("http://www.datamodelextension.org", "LATE_CHARGE_RULES");
    private final static QName _TotalOptionalPaymentCount_QNAME = new QName("http://www.datamodelextension.org", "TotalOptionalPaymentCount");
    private final static QName _SubordinateFinancingIsNewIndicator_QNAME = new QName("http://www.datamodelextension.org", "SubordinateFinancingIsNewIndicator");
    private final static QName _TotalStepPaymentCount_QNAME = new QName("http://www.datamodelextension.org", "TotalStepPaymentCount");
    private final static QName _TotalStepCount_QNAME = new QName("http://www.datamodelextension.org", "TotalStepCount");
    private final static QName _DocumentSignatureRequiredIndicator_QNAME = new QName("http://www.datamodelextension.org", "DocumentSignatureRequiredIndicator");
    private final static QName _LiabilitySecuredBySubjectPropertyIndicator_QNAME = new QName("http://www.datamodelextension.org", "LiabilitySecuredBySubjectPropertyIndicator");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.datamodelextension
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link LATECHARGERULES }
     * 
     */
    public LATECHARGERULES createLATECHARGERULES() {
        return new LATECHARGERULES();
    }

    /**
     * Create an instance of {@link IntegratedDisclosureSectionEnum }
     * 
     */
    public IntegratedDisclosureSectionEnum createIntegratedDisclosureSectionEnum() {
        return new IntegratedDisclosureSectionEnum();
    }

    /**
     * Create an instance of {@link CLOSINGADJUSTMENTITEMPAIDTO }
     * 
     */
    public CLOSINGADJUSTMENTITEMPAIDTO createCLOSINGADJUSTMENTITEMPAIDTO() {
        return new CLOSINGADJUSTMENTITEMPAIDTO();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CLOSINGADJUSTMENTITEMPAIDTO }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.datamodelextension.org", name = "CLOSING_ADJUSTMENT_ITEM_PAID_TO")
    public JAXBElement<CLOSINGADJUSTMENTITEMPAIDTO> createCLOSINGADJUSTMENTITEMPAIDTO(CLOSINGADJUSTMENTITEMPAIDTO value) {
        return new JAXBElement<CLOSINGADJUSTMENTITEMPAIDTO>(_CLOSINGADJUSTMENTITEMPAIDTO_QNAME, CLOSINGADJUSTMENTITEMPAIDTO.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.datamodelextension.org", name = "BuydownReflectedInNoteIndicator")
    public JAXBElement<Boolean> createBuydownReflectedInNoteIndicator(Boolean value) {
        return new JAXBElement<Boolean>(_BuydownReflectedInNoteIndicator_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IntegratedDisclosureSectionEnum }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.datamodelextension.org", name = "IntegratedDisclosureSectionType")
    public JAXBElement<IntegratedDisclosureSectionEnum> createIntegratedDisclosureSectionType(IntegratedDisclosureSectionEnum value) {
        return new JAXBElement<IntegratedDisclosureSectionEnum>(_IntegratedDisclosureSectionType_QNAME, IntegratedDisclosureSectionEnum.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LATECHARGERULES }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.datamodelextension.org", name = "LATE_CHARGE_RULES")
    public JAXBElement<LATECHARGERULES> createLATECHARGERULES(LATECHARGERULES value) {
        return new JAXBElement<LATECHARGERULES>(_LATECHARGERULES_QNAME, LATECHARGERULES.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.datamodelextension.org", name = "TotalOptionalPaymentCount")
    public JAXBElement<Integer> createTotalOptionalPaymentCount(Integer value) {
        return new JAXBElement<Integer>(_TotalOptionalPaymentCount_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.datamodelextension.org", name = "SubordinateFinancingIsNewIndicator")
    public JAXBElement<Boolean> createSubordinateFinancingIsNewIndicator(Boolean value) {
        return new JAXBElement<Boolean>(_SubordinateFinancingIsNewIndicator_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.datamodelextension.org", name = "TotalStepPaymentCount")
    public JAXBElement<Integer> createTotalStepPaymentCount(Integer value) {
        return new JAXBElement<Integer>(_TotalStepPaymentCount_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.datamodelextension.org", name = "TotalStepCount")
    public JAXBElement<Integer> createTotalStepCount(Integer value) {
        return new JAXBElement<Integer>(_TotalStepCount_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.datamodelextension.org", name = "DocumentSignatureRequiredIndicator")
    public JAXBElement<Boolean> createDocumentSignatureRequiredIndicator(Boolean value) {
        return new JAXBElement<Boolean>(_DocumentSignatureRequiredIndicator_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.datamodelextension.org", name = "LiabilitySecuredBySubjectPropertyIndicator")
    public JAXBElement<Boolean> createLiabilitySecuredBySubjectPropertyIndicator(Boolean value) {
        return new JAXBElement<Boolean>(_LiabilitySecuredBySubjectPropertyIndicator_QNAME, Boolean.class, null, value);
    }

}
